use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::Path;

use serde_json::json;

use crate::{list_internal_crate_import_edges, CommandError, Model, RepoHandle};

pub const GENERATED_MODEL_PATH: &str = "c4/model.generated.yml";
pub const SCHEMA_PATH: &str = "c4/schema.json";
pub const BUNDLED_MODEL_SCHEMA_JSON: &str = include_str!("./model_schema.json");
pub const GENERATED_MODEL_HEADER: &str = "# c4/model.generated.yml
# Regenerated by c4lens. Do not hand-edit; edit c4/model.yml instead.
# yaml-language-server: $schema=./schema.json
";

#[derive(Debug, Clone)]
pub struct SingleAuthoredInternalSystem {
    pub slug: String,
    pub name: String,
}

pub fn build_minimal_generated_model(repo: &RepoHandle) -> Model {
    build_minimal_generated_model_from_authored_system(repo, None)
}

pub fn build_minimal_generated_model_from_authored_system(
    repo: &RepoHandle,
    authored_internal_system: Option<&SingleAuthoredInternalSystem>,
) -> Model {
    let root_path = Path::new(&repo.root_path);
    let mut containers = Vec::new();
    let mut has_root_manifest = false;

    if let Some(container) = detect_root_cargo_manifest(root_path, &repo.name) {
        containers.push(container);
        has_root_manifest = true;
    }

    if let Some(container) = detect_root_package_json_manifest(root_path, &repo.name) {
        containers.push(container);
        has_root_manifest = true;
    }

    if let Some(container) = detect_root_go_mod_manifest(root_path, &repo.name) {
        containers.push(container);
        has_root_manifest = true;
    }

    if let Some(container) = detect_root_pyproject_toml_manifest(root_path, &repo.name) {
        containers.push(container);
        has_root_manifest = true;
    }

    if let Some(container) =
        detect_root_requirements_txt_manifest(root_path, root_path.join("pyproject.toml").is_file())
    {
        containers.push(container);
        has_root_manifest = true;
    }

    if let Some(container) = detect_root_gemfile_manifest(root_path) {
        containers.push(container);
        has_root_manifest = true;
    }

    for container in detect_root_docker_compose_services_manifest(root_path) {
        containers.push(container);
        has_root_manifest = true;
    }

    if !has_root_manifest {
        if let Some(container) = detect_root_dockerfile_manifest(root_path) {
            containers.push(container);
        }
    }

    let mut systems = BTreeMap::new();
    let mut relationships = Vec::new();
    let mut generated_components = Vec::new();

    if !containers.is_empty() {
        let (system_slug, system_name) = match authored_internal_system {
            Some(system) => (system.slug.clone(), system.name.clone()),
            None => (slugify(&repo.name), titleize(&repo.name)),
        };

        let authored_collision_index = build_authored_container_collision_index(repo);
        let mut reserved_slugs = BTreeSet::new();
        reserved_slugs.insert(system_slug.clone());

        let mut generated_system = crate::System {
            base: crate::BaseElement {
                slug: system_slug.clone(),
                name: system_name,
                description: None,
                tech: None,
                status: Default::default(),
                code: None,
                generated: true,
            },
            external: false,
            containers: BTreeMap::new(),
        };

        for container in containers.drain(..) {
            let container_slug = resolve_generated_container_slug(
                &container.slug,
                &system_slug,
                &reserved_slugs,
                authored_collision_index.as_ref(),
            );
            let container_code = container.code;
            let dependency_targets = container.dependency_targets;
            reserved_slugs.insert(container_slug.clone());
            let components = build_generated_container_components(
                root_path,
                &container_slug,
                &container_code,
                &mut reserved_slugs,
                authored_collision_index.as_ref(),
            );
            collect_generated_components_for_container_imports(
                &components,
                &mut generated_components,
            );

            generated_system.containers.insert(
                container_slug.clone(),
                crate::Container {
                    base: crate::BaseElement {
                        slug: container_slug.clone(),
                        name: container.name,
                        description: None,
                        tech: container.tech,
                        status: Default::default(),
                        code: Some(container_code.clone()),
                        generated: true,
                    },
                    kind: Default::default(),
                    components,
                },
            );

            for (dependency_slug, dependency_kind) in dependency_targets {
                let dependency_name = dependency_display_name(&dependency_slug);

                match dependency_kind {
                    PackageJsonDependencyKind::ExternalSystem => {
                        let external_system_slug = resolve_generated_system_slug(
                            &dependency_slug,
                            &reserved_slugs,
                            authored_collision_index.as_ref(),
                        );
                        reserved_slugs.insert(external_system_slug.clone());

                        if !systems.contains_key(&external_system_slug) {
                            systems.insert(
                                external_system_slug.clone(),
                                crate::System {
                                    base: crate::BaseElement {
                                        slug: external_system_slug.clone(),
                                        name: dependency_name,
                                        description: None,
                                        tech: None,
                                        status: Default::default(),
                                        code: None,
                                        generated: true,
                                    },
                                    external: true,
                                    containers: BTreeMap::new(),
                                },
                            );
                        }

                        relationships.push(crate::Relationship {
                            from: container_slug.clone(),
                            to: external_system_slug.clone(),
                            description: format!("Uses {}", dependency_slug),
                            tech: None,
                            status: Default::default(),
                            generated: true,
                        });
                    }
                    PackageJsonDependencyKind::StoreContainer => {
                        let store_container_slug = resolve_generated_store_container_slug(
                            &dependency_slug,
                            &system_slug,
                            &reserved_slugs,
                            authored_collision_index.as_ref(),
                        );
                        let reuses_authored_store = authored_store_container_exists(
                            &store_container_slug,
                            &system_slug,
                            authored_collision_index.as_ref(),
                        );
                        reserved_slugs.insert(store_container_slug.clone());

                        if !generated_system
                            .containers
                            .contains_key(&store_container_slug)
                            && !reuses_authored_store
                        {
                            generated_system.containers.insert(
                                store_container_slug.clone(),
                                crate::Container {
                                    base: crate::BaseElement {
                                        slug: store_container_slug.clone(),
                                        name: dependency_name,
                                        description: None,
                                        tech: None,
                                        status: Default::default(),
                                        code: None,
                                        generated: true,
                                    },
                                    kind: crate::ContainerKind::Store,
                                    components: BTreeMap::new(),
                                },
                            );
                        }

                        relationships.push(crate::Relationship {
                            from: container_slug.clone(),
                            to: store_container_slug,
                            description: format!("Uses {}", dependency_slug),
                            tech: None,
                            status: Default::default(),
                            generated: true,
                        });
                    }
                }
            }
        }

        relationships.extend(build_scan_discovered_component_relationships(
            repo,
            &generated_components,
        ));

        systems.insert(system_slug, generated_system);
    }

    Model {
        name: repo.name.clone(),
        description: None,
        actors: BTreeMap::new(),
        systems,
        relationships,
        generated: true,
    }
}

#[derive(Debug, Clone)]
struct GeneratedComponentImportMetadata {
    slug: String,
    code_path: String,
}

fn collect_generated_components_for_container_imports(
    components: &BTreeMap<String, crate::Component>,
    generated_components: &mut Vec<GeneratedComponentImportMetadata>,
) {
    for (component_slug, component) in components {
        let Some(code_path) = component.base.code.as_deref() else {
            continue;
        };

        generated_components.push(GeneratedComponentImportMetadata {
            slug: component_slug.clone(),
            code_path: code_path.to_string(),
        });
    }
}

fn build_scan_discovered_component_relationships(
    repo: &RepoHandle,
    generated_components: &[GeneratedComponentImportMetadata],
) -> Vec<crate::Relationship> {
    let Ok(import_edges) = list_internal_crate_import_edges(repo, None) else {
        return Vec::new();
    };
    if import_edges.is_empty() || generated_components.is_empty() {
        return Vec::new();
    }

    let mut discovered: BTreeSet<(String, String)> = BTreeSet::new();
    for edge in import_edges {
        let Some(from_slug) = component_slug_for_file(&edge.from_file, generated_components) else {
            continue;
        };
        let Some(to_slug) = component_slug_for_file(&edge.to_file, generated_components) else {
            continue;
        };
        if from_slug == to_slug {
            continue;
        }

        discovered.insert((from_slug, to_slug));
    }

    let mut relationships = Vec::new();
    for (from, to) in discovered {
        relationships.push(crate::Relationship {
            from,
            to,
            description: "Imports".to_string(),
            tech: None,
            status: Default::default(),
            generated: true,
        });
    }

    relationships
}

fn component_slug_for_file(
    file_path: &str,
    generated_components: &[GeneratedComponentImportMetadata],
) -> Option<String> {
    generated_components
        .iter()
        .filter(|component| is_file_in_component(file_path, &component.code_path))
        .max_by_key(|component| component.code_path.len())
        .map(|component| component.slug.clone())
}

fn is_file_in_component(file_path: &str, component_code: &str) -> bool {
    file_path == component_code || file_path.starts_with(&(String::from(component_code) + "/"))
}

fn build_generated_container_components(
    repo_root: &Path,
    container_slug: &str,
    container_code: &str,
    reserved_slugs: &mut BTreeSet<String>,
    authored_collision_index: Option<&AuthoredContainerCollisionIndex>,
) -> BTreeMap<String, crate::Component> {
    if container_code == "." {
        return BTreeMap::new();
    }

    let components_root = repo_root.join(container_code);
    let repo_root = match repo_root.canonicalize() {
        Ok(path) => path,
        Err(_) => return BTreeMap::new(),
    };
    let components_root = match components_root.canonicalize() {
        Ok(path) if path.starts_with(&repo_root) => path,
        _ => return BTreeMap::new(),
    };

    let mut child_dirs = match fs::read_dir(&components_root) {
        Ok(entries) => entries,
        Err(_) => return BTreeMap::new(),
    }
    .filter_map(Result::ok)
    .filter(|entry| entry.file_type().is_ok_and(|file_type| file_type.is_dir()))
    .filter_map(|entry| {
        let name = entry.file_name();
        let name = name.to_str()?;
        let name = name.to_string();
        if is_ignored_generated_component_directory(&name) {
            return None;
        }
        if !is_valid_generated_component_code_path_segment(&name) {
            return None;
        }
        Some(name)
    })
    .collect::<Vec<_>>();

    child_dirs.sort_unstable();

    let mut components = BTreeMap::new();
    for name in child_dirs {
        let initial_slug = slugify(&name);
        let component_slug = resolve_generated_component_slug(
            &initial_slug,
            container_slug,
            reserved_slugs,
            authored_collision_index,
        );
        reserved_slugs.insert(component_slug.clone());

        components.insert(
            component_slug.clone(),
            crate::Component {
                base: crate::BaseElement {
                    slug: component_slug,
                    name: titleize(&name),
                    description: None,
                    tech: None,
                    status: Default::default(),
                    code: Some(format!("{container_code}/{name}")),
                    generated: true,
                },
            },
        );
    }

    components
}

fn resolve_generated_component_slug(
    initial_slug: &str,
    parent_slug: &str,
    used: &BTreeSet<String>,
    authored_collision_index: Option<&AuthoredContainerCollisionIndex>,
) -> String {
    let mut i = 1u32;
    loop {
        let candidate = if i == 1 {
            initial_slug.to_string()
        } else {
            format!("{initial_slug}_{i}")
        };

        if !used.contains(&candidate)
            && generated_component_slug_is_reusable(
                &candidate,
                parent_slug,
                i == 1,
                authored_collision_index,
            )
        {
            return candidate;
        }

        i += 1;
    }
}

fn generated_component_slug_is_reusable(
    slug: &str,
    parent_slug: &str,
    allow_same_parent_component_reuse: bool,
    authored_collision_index: Option<&AuthoredContainerCollisionIndex>,
) -> bool {
    let Some(index) = authored_collision_index else {
        return true;
    };

    if allow_same_parent_component_reuse {
        if let Some(components) = index.components_by_parent.get(parent_slug) {
            if components.contains(slug) {
                return true;
            }
        }
    } else if let Some(components) = index.components_by_parent.get(parent_slug) {
        if components.contains(slug) {
            return false;
        }
    }

    if index.non_component_slugs.contains(slug) {
        return false;
    }

    for (existing_parent, components) in &index.components_by_parent {
        if existing_parent != parent_slug && components.contains(slug) {
            return false;
        }
    }

    true
}

fn is_ignored_generated_component_directory(name: &str) -> bool {
    if name.starts_with('.') {
        return true;
    }

    matches!(
        name,
        "test"
            | "tests"
            | "spec"
            | "specs"
            | "__tests__"
            | "fixtures"
            | "vendor"
            | "node_modules"
            | "target"
            | "dist"
            | "build"
    )
}

fn is_valid_generated_component_code_path_segment(name: &str) -> bool {
    !name.is_empty()
        && !name.contains('/')
        && !name.contains('\\')
        && !name.contains('\0')
        && name != "."
        && name != ".."
}

pub fn single_authored_internal_system_for_generation(
    repo: &RepoHandle,
) -> Option<SingleAuthoredInternalSystem> {
    let model = crate::loader::load_authored_effective_model_from_repo(repo.clone())
        .ok()?
        .model;

    let mut internal = model
        .systems
        .into_iter()
        .filter(|(_, system)| !system.external)
        .map(|(slug, system)| SingleAuthoredInternalSystem {
            slug,
            name: system.base.name,
        });

    let first = internal.next()?;
    if internal.next().is_some() {
        return None;
    }

    Some(first)
}

#[derive(Debug, Default)]
struct AuthoredContainerCollisionIndex {
    containers_by_parent: BTreeMap<String, BTreeSet<String>>,
    store_containers_by_parent: BTreeMap<String, BTreeSet<String>>,
    components_by_parent: BTreeMap<String, BTreeSet<String>>,
    external_system_slugs: BTreeSet<String>,
    non_system_slugs: BTreeSet<String>,
    non_container_slugs: BTreeSet<String>,
    non_component_slugs: BTreeSet<String>,
}

fn build_authored_container_collision_index(
    repo: &RepoHandle,
) -> Option<AuthoredContainerCollisionIndex> {
    let authored_model =
        crate::loader::load_authored_effective_model_from_repo(repo.clone()).ok()?;
    let mut index = AuthoredContainerCollisionIndex::default();

    for actor_slug in authored_model.model.actors.keys() {
        index.non_system_slugs.insert(actor_slug.clone());
        index.non_container_slugs.insert(actor_slug.clone());
        index.non_component_slugs.insert(actor_slug.clone());
    }

    for (system_slug, system) in &authored_model.model.systems {
        if system.external {
            index.external_system_slugs.insert(system_slug.clone());
        } else {
            index.non_system_slugs.insert(system_slug.clone());
        }
        index.non_container_slugs.insert(system_slug.clone());
        index.non_component_slugs.insert(system_slug.clone());
        let containers = index
            .containers_by_parent
            .entry(system_slug.clone())
            .or_default();
        let store_containers = index
            .store_containers_by_parent
            .entry(system_slug.clone())
            .or_default();

        for (container_slug, container) in &system.containers {
            index.non_system_slugs.insert(container_slug.clone());
            containers.insert(container_slug.clone());
            if container.kind == crate::ContainerKind::Store {
                store_containers.insert(container_slug.clone());
            }
            index.non_component_slugs.insert(container_slug.clone());
        }

        for (container_slug, container) in &system.containers {
            let components = index
                .components_by_parent
                .entry(container_slug.clone())
                .or_default();
            for component_slug in container.components.keys() {
                index.non_system_slugs.insert(component_slug.clone());
                components.insert(component_slug.clone());
                index.non_container_slugs.insert(component_slug.clone());
            }
        }
    }

    Some(index)
}

fn generated_container_slug_is_reusable(
    slug: &str,
    parent_slug: &str,
    allow_same_parent_container_reuse: bool,
    authored_collision_index: Option<&AuthoredContainerCollisionIndex>,
) -> bool {
    let Some(index) = authored_collision_index else {
        return true;
    };

    if allow_same_parent_container_reuse {
        if let Some(containers) = index.containers_by_parent.get(parent_slug) {
            if containers.contains(slug) {
                return true;
            }
        }
    } else if let Some(containers) = index.containers_by_parent.get(parent_slug) {
        if containers.contains(slug) {
            return false;
        }
    }

    if index.non_container_slugs.contains(slug) {
        return false;
    }

    for (existing_parent, containers) in &index.containers_by_parent {
        if existing_parent != parent_slug && containers.contains(slug) {
            return false;
        }
    }

    true
}

fn resolve_generated_container_slug(
    initial_slug: &str,
    parent_slug: &str,
    used: &BTreeSet<String>,
    authored_collision_index: Option<&AuthoredContainerCollisionIndex>,
) -> String {
    let mut i = 1u32;
    loop {
        let candidate = if i == 1 {
            initial_slug.to_string()
        } else {
            format!("{}_{}", initial_slug, i)
        };

        if !used.contains(&candidate)
            && generated_container_slug_is_reusable(
                &candidate,
                parent_slug,
                i == 1,
                authored_collision_index,
            )
        {
            return candidate;
        }

        i += 1;
    }
}

fn resolve_generated_store_container_slug(
    initial_slug: &str,
    parent_slug: &str,
    used: &BTreeSet<String>,
    authored_collision_index: Option<&AuthoredContainerCollisionIndex>,
) -> String {
    let mut i = 1u32;
    loop {
        let candidate = if i == 1 {
            initial_slug.to_string()
        } else {
            format!("{initial_slug}_{i}")
        };

        if !used.contains(&candidate)
            && generated_store_container_slug_is_reusable(
                &candidate,
                parent_slug,
                i == 1,
                authored_collision_index,
            )
        {
            return candidate;
        }

        i += 1;
    }
}

fn generated_store_container_slug_is_reusable(
    slug: &str,
    parent_slug: &str,
    allow_same_parent_store_reuse: bool,
    authored_collision_index: Option<&AuthoredContainerCollisionIndex>,
) -> bool {
    let Some(index) = authored_collision_index else {
        return true;
    };

    if allow_same_parent_store_reuse {
        if let Some(stores) = index.store_containers_by_parent.get(parent_slug) {
            if stores.contains(slug) {
                return true;
            }
        }
    }

    if let Some(containers) = index.containers_by_parent.get(parent_slug) {
        if containers.contains(slug) {
            return false;
        }
    }

    if index.non_container_slugs.contains(slug) {
        return false;
    }

    for (existing_parent, containers) in &index.containers_by_parent {
        if existing_parent != parent_slug && containers.contains(slug) {
            return false;
        }
    }

    true
}

fn authored_store_container_exists(
    slug: &str,
    parent_slug: &str,
    authored_collision_index: Option<&AuthoredContainerCollisionIndex>,
) -> bool {
    let Some(index) = authored_collision_index else {
        return false;
    };

    index
        .store_containers_by_parent
        .get(parent_slug)
        .is_some_and(|stores| stores.contains(slug))
}

fn package_json_dependency_targets_from_manifest(
    manifest: &serde_json::Value,
) -> BTreeMap<String, PackageJsonDependencyKind> {
    let mut dependencies = BTreeMap::new();
    for section_name in ["dependencies"] {
        let Some(dependency_section) = manifest
            .get(section_name)
            .and_then(|value| value.as_object())
        else {
            continue;
        };

        for dependency_name in dependency_section.keys() {
            if let Some((dependency_slug, dependency_kind)) =
                normalize_package_json_dependency_name(dependency_name)
            {
                dependencies
                    .entry(dependency_slug)
                    .or_insert(dependency_kind);
            }
        }
    }

    dependencies
}

fn normalize_package_json_dependency_name(
    dependency_name: &str,
) -> Option<(String, PackageJsonDependencyKind)> {
    let normalized = dependency_name.to_ascii_lowercase();
    if normalized == "aws-sdk" || normalized.starts_with("@aws-sdk/") {
        return Some(("aws".to_string(), PackageJsonDependencyKind::ExternalSystem));
    }

    match normalized.as_str() {
        "pg" | "postgres" | "postgresql" => Some((
            "postgres".to_string(),
            PackageJsonDependencyKind::StoreContainer,
        )),
        "mysql" | "mysql2" => Some((
            "mysql".to_string(),
            PackageJsonDependencyKind::StoreContainer,
        )),
        "redis" => Some((
            "redis".to_string(),
            PackageJsonDependencyKind::StoreContainer,
        )),
        "mongodb" | "mongo" => Some((
            "mongodb".to_string(),
            PackageJsonDependencyKind::StoreContainer,
        )),
        "sqlite" | "rusqlite" => Some((
            "sqlite".to_string(),
            PackageJsonDependencyKind::StoreContainer,
        )),
        "stripe" | "sendgrid" | "twilio" | "sentry" => {
            Some((normalized, PackageJsonDependencyKind::ExternalSystem))
        }
        _ => None,
    }
}

fn resolve_generated_system_slug(
    initial_slug: &str,
    used: &BTreeSet<String>,
    authored_collision_index: Option<&AuthoredContainerCollisionIndex>,
) -> String {
    let mut i = 1u32;
    loop {
        let candidate = if i == 1 {
            initial_slug.to_string()
        } else {
            format!("{initial_slug}_{i}")
        };

        if !used.contains(&candidate)
            && generated_system_slug_is_reusable(&candidate, authored_collision_index)
        {
            return candidate;
        }

        i += 1;
    }
}

fn generated_system_slug_is_reusable(
    slug: &str,
    authored_collision_index: Option<&AuthoredContainerCollisionIndex>,
) -> bool {
    let Some(index) = authored_collision_index else {
        return true;
    };

    if index.external_system_slugs.contains(slug) {
        return true;
    }

    if index.non_system_slugs.contains(slug) {
        return false;
    }

    true
}

fn dependency_display_name(slug: &str) -> String {
    match slug {
        "aws" => "AWS".to_string(),
        "mongodb" => "MongoDB".to_string(),
        "postgres" => "Postgres".to_string(),
        "sqlite" => "SQLite".to_string(),
        _ => titleize(slug),
    }
}

#[derive(Debug, Clone, Copy)]
enum PackageJsonDependencyKind {
    ExternalSystem,
    StoreContainer,
}

fn detect_root_cargo_manifest(repo_root: &Path, repo_name: &str) -> Option<GeneratedContainer> {
    let manifest_path = repo_root.join("Cargo.toml");
    if !manifest_path.is_file() {
        return None;
    }

    let manifest_text = fs::read_to_string(&manifest_path).ok()?;
    let name = parse_manifest_name_in_section(&manifest_text, "package", "name", repo_name);
    let slug = slugify(&name);
    let code = if repo_root.join("src").is_dir() {
        "src".to_string()
    } else {
        ".".to_string()
    };

    Some(GeneratedContainer {
        slug,
        name: titleize(&name),
        code,
        tech: Some("Rust".to_string()),
        dependency_targets: BTreeMap::new(),
    })
}

fn detect_root_package_json_manifest(
    repo_root: &Path,
    repo_name: &str,
) -> Option<GeneratedContainer> {
    let manifest_path = repo_root.join("package.json");
    if !manifest_path.is_file() {
        return None;
    }

    let manifest_text = fs::read_to_string(&manifest_path).ok()?;
    let manifest: serde_json::Value = serde_json::from_str(&manifest_text).ok()?;
    let name = manifest
        .get("name")
        .and_then(|value| value.as_str())
        .unwrap_or(repo_name)
        .to_string();

    let slug = slugify(&name);
    let code = if repo_root.join("src").is_dir() {
        "src".to_string()
    } else if repo_root.join("app").is_dir() {
        "app".to_string()
    } else if repo_root.join("lib").is_dir() {
        "lib".to_string()
    } else {
        ".".to_string()
    };

    Some(GeneratedContainer {
        slug,
        name: titleize(&name),
        code,
        tech: Some("Node.js".to_string()),
        dependency_targets: package_json_dependency_targets_from_manifest(&manifest),
    })
}

fn detect_root_go_mod_manifest(repo_root: &Path, repo_name: &str) -> Option<GeneratedContainer> {
    let manifest_path = repo_root.join("go.mod");
    if !manifest_path.is_file() {
        return None;
    }

    let manifest_text = fs::read_to_string(&manifest_path).ok()?;
    let module_name = manifest_text
        .lines()
        .map(|line| line.split('#').next().unwrap_or("").trim())
        .find(|line| line.starts_with("module "))
        .and_then(|line| line.split_whitespace().nth(1))
        .and_then(|module_path| module_path.split('/').next_back())
        .unwrap_or(repo_name)
        .trim_end_matches(".git")
        .to_string();

    if module_name.is_empty() {
        return None;
    }

    let code = if repo_root.join("src").is_dir() {
        "src".to_string()
    } else {
        ".".to_string()
    };

    Some(GeneratedContainer {
        slug: slugify(&module_name),
        name: titleize(&module_name),
        code,
        tech: Some("Go".to_string()),
        dependency_targets: BTreeMap::new(),
    })
}

fn detect_root_pyproject_toml_manifest(
    repo_root: &Path,
    repo_name: &str,
) -> Option<GeneratedContainer> {
    let manifest_path = repo_root.join("pyproject.toml");
    if !manifest_path.is_file() {
        return None;
    }

    let manifest_text = fs::read_to_string(&manifest_path).ok()?;
    let name = parse_manifest_name_in_section(&manifest_text, "project", "name", repo_name);

    let code = if repo_root.join("src").is_dir() {
        "src".to_string()
    } else {
        ".".to_string()
    };

    Some(GeneratedContainer {
        slug: slugify(&name),
        name: titleize(&name),
        code,
        tech: Some("Python".to_string()),
        dependency_targets: BTreeMap::new(),
    })
}

fn detect_root_requirements_txt_manifest(
    repo_root: &Path,
    has_pyproject: bool,
) -> Option<GeneratedContainer> {
    if has_pyproject || !repo_root.join("requirements.txt").is_file() {
        return None;
    }

    let code = if repo_root.join("src").is_dir() {
        "src".to_string()
    } else {
        ".".to_string()
    };

    Some(GeneratedContainer {
        slug: "python".to_string(),
        name: "Python".to_string(),
        code,
        tech: Some("Python".to_string()),
        dependency_targets: BTreeMap::new(),
    })
}

fn detect_root_gemfile_manifest(repo_root: &Path) -> Option<GeneratedContainer> {
    let manifest_path = repo_root.join("Gemfile");
    if !manifest_path.is_file() {
        return None;
    }

    let manifest_text = fs::read_to_string(&manifest_path).ok()?;
    let contains_rails = gemfile_declares_gem(&manifest_text, "rails");

    let code = if repo_root.join("app").is_dir() {
        "app".to_string()
    } else if repo_root.join("src").is_dir() {
        "src".to_string()
    } else {
        ".".to_string()
    };

    Some(GeneratedContainer {
        slug: "ruby".to_string(),
        name: "Ruby".to_string(),
        code,
        tech: Some(if contains_rails {
            "Ruby on Rails".to_string()
        } else {
            "Ruby".to_string()
        }),
        dependency_targets: BTreeMap::new(),
    })
}

fn detect_root_dockerfile_manifest(repo_root: &Path) -> Option<GeneratedContainer> {
    let manifest_path = repo_root.join("Dockerfile");
    if !manifest_path.is_file() {
        return None;
    }

    Some(GeneratedContainer {
        slug: "dockerfile".to_string(),
        name: "Dockerfile".to_string(),
        code: ".".to_string(),
        tech: Some("Docker".to_string()),
        dependency_targets: BTreeMap::new(),
    })
}

fn detect_root_docker_compose_services_manifest(repo_root: &Path) -> Vec<GeneratedContainer> {
    let manifest_path = repo_root.join("docker-compose.yml");
    if !manifest_path.is_file() {
        return Vec::new();
    }

    let manifest_text = match fs::read_to_string(&manifest_path) {
        Ok(text) => text,
        Err(_) => return Vec::new(),
    };

    let manifest: serde_yaml_ng::Value = match serde_yaml_ng::from_str(&manifest_text) {
        Ok(value) => value,
        Err(_) => return Vec::new(),
    };

    let Some(manifest_map) = manifest.as_mapping() else {
        return Vec::new();
    };

    let Some(services_node) =
        manifest_map.get(serde_yaml_ng::Value::String("services".to_string()))
    else {
        return Vec::new();
    };

    let Some(services_map) = services_node.as_mapping() else {
        return Vec::new();
    };

    let mut service_names = services_map
        .iter()
        .filter_map(|(service_name_node, service_def)| {
            Some((service_name_node.as_str()?, service_def))
        })
        .collect::<Vec<_>>();
    service_names.sort_by(|(left, _), (right, _)| left.cmp(right));

    service_names
        .into_iter()
        .map(|(service_name, service_def)| {
            let code = detect_root_docker_compose_service_code(repo_root, service_def);
            GeneratedContainer {
                slug: slugify(service_name),
                name: titleize(service_name),
                code,
                tech: Some("Docker Compose".to_string()),
                dependency_targets: BTreeMap::new(),
            }
        })
        .collect()
}

fn detect_root_docker_compose_service_code(
    repo_root: &Path,
    service: &serde_yaml_ng::Value,
) -> String {
    let Some(service_map) = service.as_mapping() else {
        return ".".to_string();
    };

    let Some(build_node) = service_map.get(serde_yaml_ng::Value::String("build".to_string()))
    else {
        return ".".to_string();
    };

    let context = match build_node {
        serde_yaml_ng::Value::String(context) => Some(context.as_str()),
        serde_yaml_ng::Value::Mapping(build_map) => build_map
            .get(serde_yaml_ng::Value::String("context".to_string()))
            .and_then(serde_yaml_ng::Value::as_str),
        _ => None,
    };

    context
        .filter(|context| !context.trim().is_empty())
        .map(|context| resolve_root_docker_compose_service_code(repo_root, context))
        .unwrap_or_else(|| ".".to_string())
}

fn resolve_root_docker_compose_service_code(repo_root: &Path, build_context: &str) -> String {
    let canonical_repo_root = match repo_root.canonicalize() {
        Ok(root) => root,
        Err(_) => return ".".to_string(),
    };

    let canonical_build_context = match canonical_repo_root.join(build_context).canonicalize() {
        Ok(path) => path,
        Err(_) => return ".".to_string(),
    };

    if !canonical_build_context.is_dir() {
        return ".".to_string();
    }

    if !canonical_build_context.starts_with(&canonical_repo_root) {
        return ".".to_string();
    }

    match canonical_build_context.strip_prefix(&canonical_repo_root) {
        Ok(relative) if relative.as_os_str().is_empty() => ".".to_string(),
        Ok(relative) => relative.to_string_lossy().into_owned(),
        Err(_) => ".".to_string(),
    }
}

fn gemfile_declares_gem(text: &str, gem_name: &str) -> bool {
    for line in text.lines() {
        let line = line.split('#').next().unwrap_or("").trim_start();
        let Some(remainder) = line.strip_prefix("gem") else {
            continue;
        };
        let Some(first_character) = remainder.chars().next() else {
            continue;
        };
        if !first_character.is_ascii_whitespace() && first_character != '(' {
            continue;
        }

        let remainder = remainder.trim_start().trim_start_matches('(').trim_start();
        let declared = remainder
            .strip_prefix('"')
            .and_then(|rest| rest.split('"').next())
            .or_else(|| {
                remainder
                    .strip_prefix('\'')
                    .and_then(|rest| rest.split('\'').next())
            });

        if declared == Some(gem_name) {
            return true;
        }
    }

    false
}

fn parse_manifest_name_in_section(text: &str, section: &str, key: &str, fallback: &str) -> String {
    let section_header = format!("[{section}]");
    let mut in_section = false;

    for line in text.lines() {
        let line = line.split('#').next().unwrap_or("").trim();
        if line.is_empty() {
            continue;
        }

        if line == section_header {
            in_section = true;
            continue;
        }

        if line.starts_with('[') {
            in_section = false;
            continue;
        }

        if !in_section {
            continue;
        }

        if let Some(raw_name) = parse_toml_string_field(line, key) {
            return raw_name;
        }
    }

    fallback.to_string()
}

fn parse_toml_string_field(line: &str, key: &str) -> Option<String> {
    let mut parts = line.splitn(2, '=');
    let field = parts.next()?.trim();
    if field != key {
        return None;
    }

    let remainder = parts.next()?.trim();
    if let Some(value) = remainder
        .trim_matches(|c| c == '"')
        .strip_prefix('\'')
        .and_then(|rest| rest.strip_suffix('\''))
    {
        return Some(value.to_string());
    }

    let value = remainder
        .trim_start_matches('"')
        .trim_end_matches('"')
        .trim_matches('\'');
    if !value.is_empty() {
        return Some(value.to_string());
    }

    None
}

fn slugify(value: &str) -> String {
    let mut result = String::new();
    let mut was_sep = false;

    for ch in value.chars() {
        let normalized = ch.to_ascii_lowercase();
        if normalized.is_ascii_alphanumeric() {
            result.push(normalized);
            was_sep = false;
        } else if !result.is_empty() && !was_sep {
            result.push('_');
            was_sep = true;
        }
    }

    while result.ends_with('_') {
        result.pop();
    }

    if result.is_empty() {
        return "repo".to_string();
    }

    if !result.chars().next().unwrap().is_ascii_lowercase() {
        result = format!("x_{result}");
    }

    result
}

fn titleize(value: &str) -> String {
    let parts = value
        .split(|c: char| !c.is_ascii_alphanumeric())
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            let first = chars.next().unwrap_or_default().to_ascii_uppercase();
            let rest = chars.as_str().to_ascii_lowercase();
            format!("{first}{rest}")
        })
        .collect::<Vec<_>>();

    if parts.is_empty() {
        return "Project".to_string();
    }

    if parts.len() == 1 && parts[0].eq_ignore_ascii_case(value) {
        parts[0].clone()
    } else {
        parts.join(" ")
    }
}

struct GeneratedContainer {
    slug: String,
    name: String,
    code: String,
    tech: Option<String>,
    dependency_targets: BTreeMap<String, PackageJsonDependencyKind>,
}

pub fn render_generated_model_yaml(model: &Model) -> Result<String, CommandError> {
    let mut model_file = model.clone();
    clear_runtime_slugs(&mut model_file);
    let serialized_model = serde_yaml_ng::to_string(&model_file).map_err(|error| {
        CommandError::with_details(
            "generation.failed",
            "Failed to serialize generated model.",
            json!({
                "error": error.to_string(),
            }),
        )
    })?;

    Ok(format!("{GENERATED_MODEL_HEADER}{serialized_model}"))
}

fn clear_runtime_slugs(model: &mut Model) {
    for actor in model.actors.values_mut() {
        actor.base.slug.clear();
    }

    for system in model.systems.values_mut() {
        system.base.slug.clear();
        for container in system.containers.values_mut() {
            container.base.slug.clear();
            for component in container.components.values_mut() {
                component.base.slug.clear();
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::build_minimal_generated_model;
    use super::render_generated_model_yaml;
    use super::{slugify, titleize};
    use crate::load_effective_model_from_repo;
    use crate::repo_handle_from_path;
    use std::fs;
    use std::time::{SystemTime, UNIX_EPOCH};

    #[test]
    fn build_minimal_model_is_deterministic() {
        let root = fresh_test_dir("minimal-generated");
        let repo_dir = root.join("repo");
        fs::create_dir(&repo_dir).expect("create repo");
        let repo = repo_handle_from_path(&repo_dir).expect("repo handle");
        let first = build_minimal_generated_model(&repo);
        let second = build_minimal_generated_model(&repo);

        assert_eq!(first.name, second.name);
        assert_eq!(first.generated, second.generated);
        assert!(first.systems.is_empty());
        assert!(first.actors.is_empty());
        assert_eq!(
            render_generated_model_yaml(&first).expect("render first"),
            render_generated_model_yaml(&second).expect("render second")
        );

        cleanup(root);
    }

    #[test]
    fn generated_yaml_is_deterministic() {
        let root = fresh_test_dir("deterministic-generated-yaml");
        let repo_dir = root.join("repo");
        fs::create_dir(&repo_dir).expect("create repo");
        let repo = repo_handle_from_path(&repo_dir).expect("repo handle");

        let model = build_minimal_generated_model(&repo);
        let first = render_generated_model_yaml(&model).expect("render yaml");
        let second = render_generated_model_yaml(&model).expect("render yaml");

        assert_eq!(first, second);
        assert!(first.starts_with(super::GENERATED_MODEL_HEADER));
        assert!(first.contains("generated: true"));

        cleanup(root);
    }

    #[test]
    fn build_generated_model_from_root_cargo_manifest() {
        let root = fresh_test_dir("generated-cargo-manifest");
        let repo_dir = root.join("repo");
        fs::create_dir(&repo_dir).expect("create repo");
        fs::create_dir(repo_dir.join("src")).expect("create src");
        fs::write(
            repo_dir.join("Cargo.toml"),
            r#"[package]
name = "cool-service"
version = "0.1.0"
"#,
        )
        .expect("write cargo manifest");

        let repo = repo_handle_from_path(&repo_dir).expect("repo handle");
        let model = build_minimal_generated_model(&repo);
        let system_slug = slugify(&repo.name);
        let container_slug = slugify("cool-service");

        let generated_system = model.systems.get(&system_slug).expect("internal system");
        let container = generated_system
            .containers
            .get(&container_slug)
            .expect("generated container");

        assert_eq!(generated_system.base.name, titleize(&repo.name));
        assert!(generated_system.base.generated);
        assert_eq!(container.base.tech.as_deref(), Some("Rust"));
        assert_eq!(container.base.code.as_deref(), Some("src"));
        assert_eq!(container.base.name, titleize("cool-service"));

        cleanup(root);
    }

    #[test]
    fn rendered_manifest_model_roundtrips_through_loader_schema() {
        let root = fresh_test_dir("generated-manifest-roundtrip");
        let repo_dir = root.join("repo");
        fs::create_dir(&repo_dir).expect("create repo");
        fs::create_dir(repo_dir.join("src")).expect("create src");
        fs::create_dir(repo_dir.join("c4")).expect("create c4");
        fs::write(
            repo_dir.join("Cargo.toml"),
            r#"[package]
name = "cool-service"
version = "0.1.0"
"#,
        )
        .expect("write cargo manifest");

        let repo = repo_handle_from_path(&repo_dir).expect("repo handle");
        let model = build_minimal_generated_model(&repo);
        let yaml = render_generated_model_yaml(&model).expect("render generated yaml");
        assert!(!yaml.contains("slug:"));
        fs::write(repo_dir.join("c4/model.generated.yml"), yaml).expect("write generated model");

        let effective = load_effective_model_from_repo(repo).expect("generated model loads");

        assert!(effective.validation.ok);
        assert!(effective.model.systems.contains_key("repo"));
        assert_eq!(
            effective.model.systems["repo"].containers["cool_service"]
                .base
                .tech
                .as_deref(),
            Some("Rust")
        );

        cleanup(root);
    }

    #[test]
    fn build_generated_model_renames_colliding_container_slug() {
        let root = fresh_test_dir("generated-collision-manifest");
        let repo_dir = root.join("repo");
        fs::create_dir(&repo_dir).expect("create repo");
        fs::create_dir(repo_dir.join("src")).expect("create src");
        fs::write(
            repo_dir.join("Cargo.toml"),
            r#"[package]
name = "repo"
version = "0.1.0"
"#,
        )
        .expect("write cargo manifest");
        fs::write(repo_dir.join("package.json"), r#"{"name": "repo"}"#)
            .expect("write package manifest");

        let repo = repo_handle_from_path(&repo_dir).expect("repo handle");
        let model = build_minimal_generated_model(&repo);
        let generated_system = model
            .systems
            .get(&slugify(&repo.name))
            .expect("internal system");

        let container_slugs = generated_system
            .containers
            .keys()
            .cloned()
            .collect::<Vec<_>>();

        assert_eq!(container_slugs.len(), 2);
        assert_eq!(container_slugs[0], "repo_2");
        assert_eq!(container_slugs[1], "repo_3");
        assert!(!generated_system.containers.contains_key("repo"));

        cleanup(root);
    }

    #[test]
    fn build_generated_model_from_root_package_json_manifest() {
        let root = fresh_test_dir("generated-package-json-manifest");
        let repo_dir = root.join("web-app");
        fs::create_dir(&repo_dir).expect("create repo");
        fs::create_dir(repo_dir.join("app")).expect("create app");
        fs::write(
            repo_dir.join("package.json"),
            r#"{"name": "@acme/web-client"}"#,
        )
        .expect("write package manifest");

        let repo = repo_handle_from_path(&repo_dir).expect("repo handle");
        let model = build_minimal_generated_model(&repo);
        let generated_system = model
            .systems
            .get(&slugify(&repo.name))
            .expect("internal system");
        let container = generated_system
            .containers
            .get("acme_web_client")
            .expect("generated package container");

        assert_eq!(container.base.tech.as_deref(), Some("Node.js"));
        assert_eq!(container.base.code.as_deref(), Some("app"));
        assert_eq!(container.base.name, "Acme Web Client");

        cleanup(root);
    }

    #[test]
    fn build_generated_model_from_root_dockerfile_fallback() {
        let root = fresh_test_dir("generated-dockerfile-fallback");
        let repo_dir = root.join("repo");
        fs::create_dir(&repo_dir).expect("create repo");
        fs::write(repo_dir.join("Dockerfile"), "FROM alpine:3.20\n").expect("write dockerfile");

        let repo = repo_handle_from_path(&repo_dir).expect("repo handle");
        let model = build_minimal_generated_model(&repo);
        let generated_system = model
            .systems
            .get(&slugify(&repo.name))
            .expect("internal system");
        let container = generated_system
            .containers
            .get("dockerfile")
            .expect("generated dockerfile container");

        assert_eq!(generated_system.containers.len(), 1);
        assert_eq!(container.base.name, "Dockerfile");
        assert_eq!(container.base.tech.as_deref(), Some("Docker"));
        assert_eq!(container.base.code.as_deref(), Some("."));

        cleanup(root);
    }

    #[test]
    fn build_generated_model_from_root_gemfile_only_marks_declared_rails_gem() {
        let root = fresh_test_dir("generated-gemfile-rails-detection");
        let repo_dir = root.join("repo");
        fs::create_dir(&repo_dir).expect("create repo");
        fs::write(
            repo_dir.join("Gemfile"),
            r#"
source "https://rails-assets.org"
gem "dry-railsish"
"#,
        )
        .expect("write gemfile");

        let repo = repo_handle_from_path(&repo_dir).expect("repo handle");
        let model = build_minimal_generated_model(&repo);
        let generated_system = model
            .systems
            .get(&slugify(&repo.name))
            .expect("internal system");
        let container = generated_system
            .containers
            .get("ruby")
            .expect("generated ruby container");

        assert_eq!(container.base.tech.as_deref(), Some("Ruby"));

        fs::write(
            repo_dir.join("Gemfile"),
            r#"
source "https://rubygems.org"
gem "rails", "~> 7.1"
"#,
        )
        .expect("write gemfile");

        let model = build_minimal_generated_model(&repo);
        let generated_system = model
            .systems
            .get(&slugify(&repo.name))
            .expect("internal system");
        let container = generated_system
            .containers
            .get("ruby")
            .expect("generated ruby container");

        assert_eq!(container.base.tech.as_deref(), Some("Ruby on Rails"));

        fs::write(
            repo_dir.join("Gemfile"),
            r#"
source "https://rubygems.org"
gem("rails", "~> 7.1")
"#,
        )
        .expect("write gemfile");

        let model = build_minimal_generated_model(&repo);
        let generated_system = model
            .systems
            .get(&slugify(&repo.name))
            .expect("internal system");
        let container = generated_system
            .containers
            .get("ruby")
            .expect("generated ruby container");

        assert_eq!(container.base.tech.as_deref(), Some("Ruby on Rails"));

        cleanup(root);
    }

    #[test]
    fn slugify_prefixes_non_letter_slugs_with_x() {
        assert_eq!(slugify("123 service"), "x_123_service");
    }

    fn fresh_test_dir(name: &str) -> std::path::PathBuf {
        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system time")
            .as_nanos();
        let dir = std::env::temp_dir().join(format!("c4lens-core-generated-{name}-{now}"));
        fs::create_dir_all(&dir).expect("create test dir");
        dir
    }

    fn cleanup(root: std::path::PathBuf) {
        fs::remove_dir_all(root).ok();
    }
}
