use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::Path;

use serde_json::json;

use crate::{CommandError, Model, RepoHandle};

pub const GENERATED_MODEL_PATH: &str = "c4/model.generated.yml";
pub const SCHEMA_PATH: &str = "c4/schema.json";
pub const BUNDLED_MODEL_SCHEMA_JSON: &str = include_str!("./model_schema.json");
pub const GENERATED_MODEL_HEADER: &str = "# c4/model.generated.yml
# Regenerated by c4lens. Do not hand-edit; edit c4/model.yml instead.
# yaml-language-server: $schema=./schema.json
";

#[derive(Debug, Clone)]
pub struct SingleAuthoredInternalSystem {
    pub slug: String,
    pub name: String,
}

pub fn build_minimal_generated_model(repo: &RepoHandle) -> Model {
    build_minimal_generated_model_from_authored_system(repo, None)
}

pub fn build_minimal_generated_model_from_authored_system(
    repo: &RepoHandle,
    authored_internal_system: Option<&SingleAuthoredInternalSystem>,
) -> Model {
    let root_path = Path::new(&repo.root_path);
    let mut containers = Vec::new();

    if let Some(container) = detect_root_cargo_manifest(root_path, &repo.name) {
        containers.push(container);
    }

    if let Some(container) = detect_root_package_json_manifest(root_path, &repo.name) {
        containers.push(container);
    }

    if let Some(container) = detect_root_go_mod_manifest(root_path, &repo.name) {
        containers.push(container);
    }

    if let Some(container) = detect_root_pyproject_toml_manifest(root_path, &repo.name) {
        containers.push(container);
    }

    if let Some(container) =
        detect_root_requirements_txt_manifest(root_path, root_path.join("pyproject.toml").is_file())
    {
        containers.push(container);
    }

    if let Some(container) = detect_root_gemfile_manifest(root_path) {
        containers.push(container);
    }

    let mut systems = BTreeMap::new();
    if !containers.is_empty() {
        let (system_slug, system_name) = match authored_internal_system {
            Some(system) => (system.slug.clone(), system.name.clone()),
            None => (slugify(&repo.name), titleize(&repo.name)),
        };

        let authored_collision_index = build_authored_container_collision_index(repo);
        let mut reserved_slugs = BTreeSet::new();
        reserved_slugs.insert(system_slug.clone());

        let mut generated_system = crate::System {
            base: crate::BaseElement {
                slug: system_slug.clone(),
                name: system_name,
                description: None,
                tech: None,
                status: Default::default(),
                code: None,
                generated: true,
            },
            external: false,
            containers: BTreeMap::new(),
        };

        for container in containers.drain(..) {
            let container_slug = resolve_generated_container_slug(
                &container.slug,
                &system_slug,
                &reserved_slugs,
                authored_collision_index.as_ref(),
            );
            reserved_slugs.insert(container_slug.clone());

            generated_system.containers.insert(
                container_slug.clone(),
                crate::Container {
                    base: crate::BaseElement {
                        slug: container_slug,
                        name: container.name,
                        description: None,
                        tech: container.tech,
                        status: Default::default(),
                        code: Some(container.code),
                        generated: true,
                    },
                    kind: Default::default(),
                    components: BTreeMap::new(),
                },
            );
        }

        systems.insert(system_slug, generated_system);
    }

    Model {
        name: repo.name.clone(),
        description: None,
        actors: BTreeMap::new(),
        systems,
        relationships: Vec::new(),
        generated: true,
    }
}

pub fn single_authored_internal_system_for_generation(
    repo: &RepoHandle,
) -> Option<SingleAuthoredInternalSystem> {
    let model = crate::loader::load_authored_effective_model_from_repo(repo.clone())
        .ok()?
        .model;

    let mut internal = model
        .systems
        .into_iter()
        .filter(|(_, system)| !system.external)
        .map(|(slug, system)| SingleAuthoredInternalSystem {
            slug,
            name: system.base.name,
        });

    let first = internal.next()?;
    if internal.next().is_some() {
        return None;
    }

    Some(first)
}

#[derive(Debug, Default)]
struct AuthoredContainerCollisionIndex {
    containers_by_parent: BTreeMap<String, BTreeSet<String>>,
    non_container_slugs: BTreeSet<String>,
}

fn build_authored_container_collision_index(
    repo: &RepoHandle,
) -> Option<AuthoredContainerCollisionIndex> {
    let authored_model =
        crate::loader::load_authored_effective_model_from_repo(repo.clone()).ok()?;
    let mut index = AuthoredContainerCollisionIndex::default();

    for actor_slug in authored_model.model.actors.keys() {
        index.non_container_slugs.insert(actor_slug.clone());
    }

    for (system_slug, system) in &authored_model.model.systems {
        index.non_container_slugs.insert(system_slug.clone());
        let containers = index
            .containers_by_parent
            .entry(system_slug.clone())
            .or_default();

        for container_slug in system.containers.keys() {
            containers.insert(container_slug.clone());
        }

        for container in system.containers.values() {
            for component_slug in container.components.keys() {
                index.non_container_slugs.insert(component_slug.clone());
            }
        }
    }

    Some(index)
}

fn generated_container_slug_is_reusable(
    slug: &str,
    parent_slug: &str,
    allow_same_parent_container_reuse: bool,
    authored_collision_index: Option<&AuthoredContainerCollisionIndex>,
) -> bool {
    let Some(index) = authored_collision_index else {
        return true;
    };

    if allow_same_parent_container_reuse {
        if let Some(containers) = index.containers_by_parent.get(parent_slug) {
            if containers.contains(slug) {
                return true;
            }
        }
    } else if let Some(containers) = index.containers_by_parent.get(parent_slug) {
        if containers.contains(slug) {
            return false;
        }
    }

    if index.non_container_slugs.contains(slug) {
        return false;
    }

    for (existing_parent, containers) in &index.containers_by_parent {
        if existing_parent != parent_slug && containers.contains(slug) {
            return false;
        }
    }

    true
}

fn resolve_generated_container_slug(
    initial_slug: &str,
    parent_slug: &str,
    used: &BTreeSet<String>,
    authored_collision_index: Option<&AuthoredContainerCollisionIndex>,
) -> String {
    let mut i = 1u32;
    loop {
        let candidate = if i == 1 {
            initial_slug.to_string()
        } else {
            format!("{}_{}", initial_slug, i)
        };

        if !used.contains(&candidate)
            && generated_container_slug_is_reusable(
                &candidate,
                parent_slug,
                i == 1,
                authored_collision_index,
            )
        {
            return candidate;
        }

        i += 1;
    }
}

fn detect_root_cargo_manifest(repo_root: &Path, repo_name: &str) -> Option<GeneratedContainer> {
    let manifest_path = repo_root.join("Cargo.toml");
    if !manifest_path.is_file() {
        return None;
    }

    let manifest_text = fs::read_to_string(&manifest_path).ok()?;
    let name = parse_manifest_name_in_section(&manifest_text, "package", "name", repo_name);
    let slug = slugify(&name);
    let code = if repo_root.join("src").is_dir() {
        "src".to_string()
    } else {
        ".".to_string()
    };

    Some(GeneratedContainer {
        slug,
        name: titleize(&name),
        code,
        tech: Some("Rust".to_string()),
    })
}

fn detect_root_package_json_manifest(
    repo_root: &Path,
    repo_name: &str,
) -> Option<GeneratedContainer> {
    let manifest_path = repo_root.join("package.json");
    if !manifest_path.is_file() {
        return None;
    }

    let manifest_text = fs::read_to_string(&manifest_path).ok()?;
    let manifest: serde_json::Value = serde_json::from_str(&manifest_text).ok()?;
    let name = manifest
        .get("name")
        .and_then(|value| value.as_str())
        .unwrap_or(repo_name)
        .to_string();

    let slug = slugify(&name);
    let code = if repo_root.join("src").is_dir() {
        "src".to_string()
    } else if repo_root.join("app").is_dir() {
        "app".to_string()
    } else if repo_root.join("lib").is_dir() {
        "lib".to_string()
    } else {
        ".".to_string()
    };

    Some(GeneratedContainer {
        slug,
        name: titleize(&name),
        code,
        tech: Some("Node.js".to_string()),
    })
}

fn detect_root_go_mod_manifest(repo_root: &Path, repo_name: &str) -> Option<GeneratedContainer> {
    let manifest_path = repo_root.join("go.mod");
    if !manifest_path.is_file() {
        return None;
    }

    let manifest_text = fs::read_to_string(&manifest_path).ok()?;
    let module_name = manifest_text
        .lines()
        .map(|line| line.split('#').next().unwrap_or("").trim())
        .find(|line| line.starts_with("module "))
        .and_then(|line| line.split_whitespace().nth(1))
        .and_then(|module_path| module_path.split('/').next_back())
        .unwrap_or(repo_name)
        .trim_end_matches(".git")
        .to_string();

    if module_name.is_empty() {
        return None;
    }

    let code = if repo_root.join("src").is_dir() {
        "src".to_string()
    } else {
        ".".to_string()
    };

    Some(GeneratedContainer {
        slug: slugify(&module_name),
        name: titleize(&module_name),
        code,
        tech: Some("Go".to_string()),
    })
}

fn detect_root_pyproject_toml_manifest(
    repo_root: &Path,
    repo_name: &str,
) -> Option<GeneratedContainer> {
    let manifest_path = repo_root.join("pyproject.toml");
    if !manifest_path.is_file() {
        return None;
    }

    let manifest_text = fs::read_to_string(&manifest_path).ok()?;
    let name = parse_manifest_name_in_section(&manifest_text, "project", "name", repo_name);

    let code = if repo_root.join("src").is_dir() {
        "src".to_string()
    } else {
        ".".to_string()
    };

    Some(GeneratedContainer {
        slug: slugify(&name),
        name: titleize(&name),
        code,
        tech: Some("Python".to_string()),
    })
}

fn detect_root_requirements_txt_manifest(
    repo_root: &Path,
    has_pyproject: bool,
) -> Option<GeneratedContainer> {
    if has_pyproject || !repo_root.join("requirements.txt").is_file() {
        return None;
    }

    let code = if repo_root.join("src").is_dir() {
        "src".to_string()
    } else {
        ".".to_string()
    };

    Some(GeneratedContainer {
        slug: "python".to_string(),
        name: "Python".to_string(),
        code,
        tech: Some("Python".to_string()),
    })
}

fn detect_root_gemfile_manifest(repo_root: &Path) -> Option<GeneratedContainer> {
    let manifest_path = repo_root.join("Gemfile");
    if !manifest_path.is_file() {
        return None;
    }

    let manifest_text = fs::read_to_string(&manifest_path).ok()?;
    let contains_rails = gemfile_declares_gem(&manifest_text, "rails");

    let code = if repo_root.join("app").is_dir() {
        "app".to_string()
    } else if repo_root.join("src").is_dir() {
        "src".to_string()
    } else {
        ".".to_string()
    };

    Some(GeneratedContainer {
        slug: "ruby".to_string(),
        name: "Ruby".to_string(),
        code,
        tech: Some(if contains_rails {
            "Ruby on Rails".to_string()
        } else {
            "Ruby".to_string()
        }),
    })
}

fn gemfile_declares_gem(text: &str, gem_name: &str) -> bool {
    for line in text.lines() {
        let line = line.split('#').next().unwrap_or("").trim_start();
        let Some(remainder) = line.strip_prefix("gem") else {
            continue;
        };
        let Some(first_character) = remainder.chars().next() else {
            continue;
        };
        if !first_character.is_ascii_whitespace() && first_character != '(' {
            continue;
        }

        let remainder = remainder.trim_start().trim_start_matches('(').trim_start();
        let declared = remainder
            .strip_prefix('"')
            .and_then(|rest| rest.split('"').next())
            .or_else(|| {
                remainder
                    .strip_prefix('\'')
                    .and_then(|rest| rest.split('\'').next())
            });

        if declared == Some(gem_name) {
            return true;
        }
    }

    false
}

fn parse_manifest_name_in_section(text: &str, section: &str, key: &str, fallback: &str) -> String {
    let section_header = format!("[{section}]");
    let mut in_section = false;

    for line in text.lines() {
        let line = line.split('#').next().unwrap_or("").trim();
        if line.is_empty() {
            continue;
        }

        if line == section_header {
            in_section = true;
            continue;
        }

        if line.starts_with('[') {
            in_section = false;
            continue;
        }

        if !in_section {
            continue;
        }

        if let Some(raw_name) = parse_toml_string_field(line, key) {
            return raw_name;
        }
    }

    fallback.to_string()
}

fn parse_toml_string_field(line: &str, key: &str) -> Option<String> {
    let mut parts = line.splitn(2, '=');
    let field = parts.next()?.trim();
    if field != key {
        return None;
    }

    let remainder = parts.next()?.trim();
    if let Some(value) = remainder
        .trim_matches(|c| c == '"')
        .strip_prefix('\'')
        .and_then(|rest| rest.strip_suffix('\''))
    {
        return Some(value.to_string());
    }

    let value = remainder
        .trim_start_matches('"')
        .trim_end_matches('"')
        .trim_matches('\'');
    if !value.is_empty() {
        return Some(value.to_string());
    }

    None
}

fn slugify(value: &str) -> String {
    let mut result = String::new();
    let mut was_sep = false;

    for ch in value.chars() {
        let normalized = ch.to_ascii_lowercase();
        if normalized.is_ascii_alphanumeric() {
            result.push(normalized);
            was_sep = false;
        } else if !result.is_empty() && !was_sep {
            result.push('_');
            was_sep = true;
        }
    }

    while result.ends_with('_') {
        result.pop();
    }

    if result.is_empty() {
        return "repo".to_string();
    }

    if !result.chars().next().unwrap().is_ascii_lowercase() {
        result = format!("x_{result}");
    }

    result
}

fn titleize(value: &str) -> String {
    let parts = value
        .split(|c: char| !c.is_ascii_alphanumeric())
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            let first = chars.next().unwrap_or_default().to_ascii_uppercase();
            let rest = chars.as_str().to_ascii_lowercase();
            format!("{first}{rest}")
        })
        .collect::<Vec<_>>();

    if parts.is_empty() {
        return "Project".to_string();
    }

    if parts.len() == 1 && parts[0].eq_ignore_ascii_case(value) {
        parts[0].clone()
    } else {
        parts.join(" ")
    }
}

struct GeneratedContainer {
    slug: String,
    name: String,
    code: String,
    tech: Option<String>,
}

pub fn render_generated_model_yaml(model: &Model) -> Result<String, CommandError> {
    let mut model_file = model.clone();
    clear_runtime_slugs(&mut model_file);
    let serialized_model = serde_yaml_ng::to_string(&model_file).map_err(|error| {
        CommandError::with_details(
            "generation.failed",
            "Failed to serialize generated model.",
            json!({
                "error": error.to_string(),
            }),
        )
    })?;

    Ok(format!("{GENERATED_MODEL_HEADER}{serialized_model}"))
}

fn clear_runtime_slugs(model: &mut Model) {
    for actor in model.actors.values_mut() {
        actor.base.slug.clear();
    }

    for system in model.systems.values_mut() {
        system.base.slug.clear();
        for container in system.containers.values_mut() {
            container.base.slug.clear();
            for component in container.components.values_mut() {
                component.base.slug.clear();
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::build_minimal_generated_model;
    use super::render_generated_model_yaml;
    use super::{slugify, titleize};
    use crate::load_effective_model_from_repo;
    use crate::repo_handle_from_path;
    use std::fs;
    use std::time::{SystemTime, UNIX_EPOCH};

    #[test]
    fn build_minimal_model_is_deterministic() {
        let root = fresh_test_dir("minimal-generated");
        let repo_dir = root.join("repo");
        fs::create_dir(&repo_dir).expect("create repo");
        let repo = repo_handle_from_path(&repo_dir).expect("repo handle");
        let first = build_minimal_generated_model(&repo);
        let second = build_minimal_generated_model(&repo);

        assert_eq!(first.name, second.name);
        assert_eq!(first.generated, second.generated);
        assert!(first.systems.is_empty());
        assert!(first.actors.is_empty());
        assert_eq!(
            render_generated_model_yaml(&first).expect("render first"),
            render_generated_model_yaml(&second).expect("render second")
        );

        cleanup(root);
    }

    #[test]
    fn generated_yaml_is_deterministic() {
        let root = fresh_test_dir("deterministic-generated-yaml");
        let repo_dir = root.join("repo");
        fs::create_dir(&repo_dir).expect("create repo");
        let repo = repo_handle_from_path(&repo_dir).expect("repo handle");

        let model = build_minimal_generated_model(&repo);
        let first = render_generated_model_yaml(&model).expect("render yaml");
        let second = render_generated_model_yaml(&model).expect("render yaml");

        assert_eq!(first, second);
        assert!(first.starts_with(super::GENERATED_MODEL_HEADER));
        assert!(first.contains("generated: true"));

        cleanup(root);
    }

    #[test]
    fn build_generated_model_from_root_cargo_manifest() {
        let root = fresh_test_dir("generated-cargo-manifest");
        let repo_dir = root.join("repo");
        fs::create_dir(&repo_dir).expect("create repo");
        fs::create_dir(repo_dir.join("src")).expect("create src");
        fs::write(
            repo_dir.join("Cargo.toml"),
            r#"[package]
name = "cool-service"
version = "0.1.0"
"#,
        )
        .expect("write cargo manifest");

        let repo = repo_handle_from_path(&repo_dir).expect("repo handle");
        let model = build_minimal_generated_model(&repo);
        let system_slug = slugify(&repo.name);
        let container_slug = slugify("cool-service");

        let generated_system = model.systems.get(&system_slug).expect("internal system");
        let container = generated_system
            .containers
            .get(&container_slug)
            .expect("generated container");

        assert_eq!(generated_system.base.name, titleize(&repo.name));
        assert!(generated_system.base.generated);
        assert_eq!(container.base.tech.as_deref(), Some("Rust"));
        assert_eq!(container.base.code.as_deref(), Some("src"));
        assert_eq!(container.base.name, titleize("cool-service"));

        cleanup(root);
    }

    #[test]
    fn rendered_manifest_model_roundtrips_through_loader_schema() {
        let root = fresh_test_dir("generated-manifest-roundtrip");
        let repo_dir = root.join("repo");
        fs::create_dir(&repo_dir).expect("create repo");
        fs::create_dir(repo_dir.join("src")).expect("create src");
        fs::create_dir(repo_dir.join("c4")).expect("create c4");
        fs::write(
            repo_dir.join("Cargo.toml"),
            r#"[package]
name = "cool-service"
version = "0.1.0"
"#,
        )
        .expect("write cargo manifest");

        let repo = repo_handle_from_path(&repo_dir).expect("repo handle");
        let model = build_minimal_generated_model(&repo);
        let yaml = render_generated_model_yaml(&model).expect("render generated yaml");
        assert!(!yaml.contains("slug:"));
        fs::write(repo_dir.join("c4/model.generated.yml"), yaml).expect("write generated model");

        let effective = load_effective_model_from_repo(repo).expect("generated model loads");

        assert!(effective.validation.ok);
        assert!(effective.model.systems.contains_key("repo"));
        assert_eq!(
            effective.model.systems["repo"].containers["cool_service"]
                .base
                .tech
                .as_deref(),
            Some("Rust")
        );

        cleanup(root);
    }

    #[test]
    fn build_generated_model_renames_colliding_container_slug() {
        let root = fresh_test_dir("generated-collision-manifest");
        let repo_dir = root.join("repo");
        fs::create_dir(&repo_dir).expect("create repo");
        fs::create_dir(repo_dir.join("src")).expect("create src");
        fs::write(
            repo_dir.join("Cargo.toml"),
            r#"[package]
name = "repo"
version = "0.1.0"
"#,
        )
        .expect("write cargo manifest");
        fs::write(repo_dir.join("package.json"), r#"{"name": "repo"}"#)
            .expect("write package manifest");

        let repo = repo_handle_from_path(&repo_dir).expect("repo handle");
        let model = build_minimal_generated_model(&repo);
        let generated_system = model
            .systems
            .get(&slugify(&repo.name))
            .expect("internal system");

        let container_slugs = generated_system
            .containers
            .keys()
            .cloned()
            .collect::<Vec<_>>();

        assert_eq!(container_slugs.len(), 2);
        assert_eq!(container_slugs[0], "repo_2");
        assert_eq!(container_slugs[1], "repo_3");
        assert!(!generated_system.containers.contains_key("repo"));

        cleanup(root);
    }

    #[test]
    fn build_generated_model_from_root_package_json_manifest() {
        let root = fresh_test_dir("generated-package-json-manifest");
        let repo_dir = root.join("web-app");
        fs::create_dir(&repo_dir).expect("create repo");
        fs::create_dir(repo_dir.join("app")).expect("create app");
        fs::write(
            repo_dir.join("package.json"),
            r#"{"name": "@acme/web-client"}"#,
        )
        .expect("write package manifest");

        let repo = repo_handle_from_path(&repo_dir).expect("repo handle");
        let model = build_minimal_generated_model(&repo);
        let generated_system = model
            .systems
            .get(&slugify(&repo.name))
            .expect("internal system");
        let container = generated_system
            .containers
            .get("acme_web_client")
            .expect("generated package container");

        assert_eq!(container.base.tech.as_deref(), Some("Node.js"));
        assert_eq!(container.base.code.as_deref(), Some("app"));
        assert_eq!(container.base.name, "Acme Web Client");

        cleanup(root);
    }

    #[test]
    fn build_generated_model_from_root_gemfile_only_marks_declared_rails_gem() {
        let root = fresh_test_dir("generated-gemfile-rails-detection");
        let repo_dir = root.join("repo");
        fs::create_dir(&repo_dir).expect("create repo");
        fs::write(
            repo_dir.join("Gemfile"),
            r#"
source "https://rails-assets.org"
gem "dry-railsish"
"#,
        )
        .expect("write gemfile");

        let repo = repo_handle_from_path(&repo_dir).expect("repo handle");
        let model = build_minimal_generated_model(&repo);
        let generated_system = model
            .systems
            .get(&slugify(&repo.name))
            .expect("internal system");
        let container = generated_system
            .containers
            .get("ruby")
            .expect("generated ruby container");

        assert_eq!(container.base.tech.as_deref(), Some("Ruby"));

        fs::write(
            repo_dir.join("Gemfile"),
            r#"
source "https://rubygems.org"
gem "rails", "~> 7.1"
"#,
        )
        .expect("write gemfile");

        let model = build_minimal_generated_model(&repo);
        let generated_system = model
            .systems
            .get(&slugify(&repo.name))
            .expect("internal system");
        let container = generated_system
            .containers
            .get("ruby")
            .expect("generated ruby container");

        assert_eq!(container.base.tech.as_deref(), Some("Ruby on Rails"));

        fs::write(
            repo_dir.join("Gemfile"),
            r#"
source "https://rubygems.org"
gem("rails", "~> 7.1")
"#,
        )
        .expect("write gemfile");

        let model = build_minimal_generated_model(&repo);
        let generated_system = model
            .systems
            .get(&slugify(&repo.name))
            .expect("internal system");
        let container = generated_system
            .containers
            .get("ruby")
            .expect("generated ruby container");

        assert_eq!(container.base.tech.as_deref(), Some("Ruby on Rails"));

        cleanup(root);
    }

    #[test]
    fn slugify_prefixes_non_letter_slugs_with_x() {
        assert_eq!(slugify("123 service"), "x_123_service");
    }

    fn fresh_test_dir(name: &str) -> std::path::PathBuf {
        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system time")
            .as_nanos();
        let dir = std::env::temp_dir().join(format!("c4lens-core-generated-{name}-{now}"));
        fs::create_dir_all(&dir).expect("create test dir");
        dir
    }

    fn cleanup(root: std::path::PathBuf) {
        fs::remove_dir_all(root).ok();
    }
}
