use std::fs;
use std::path::PathBuf;
use std::time::{SystemTime, UNIX_EPOCH};

use assert_cmd::Command;
use c4lens_core::{acquire_repo_write_lock, repo_handle_from_path};
use serde_json::Value;

#[test]
fn generate_does_not_write_without_write_flag() {
    let repo = fresh_test_dir("generate-non-write");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--repo"])
        .arg(&repo)
        .assert()
        .success();
    let output = String::from_utf8_lossy(&assert.get_output().stdout).to_string();

    assert!(
        output.starts_with(
            "# c4/model.generated.yml\n# Regenerated by c4lens. Do not hand-edit; edit c4/model.yml instead.\n# yaml-language-server: $schema=./schema.json\n"
        )
    );
    assert!(!repo.join("c4").is_dir());

    cleanup(repo);
}

#[test]
fn generate_write_creates_generated_overlay_without_model_yaml() {
    let repo = fresh_test_dir("generate-write");

    Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--write", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let generated_path = repo.join("c4/model.generated.yml");
    assert!(generated_path.is_file());
    let schema_path = repo.join("c4/schema.json");
    assert!(schema_path.is_file());
    assert!(!repo.join("c4/model.yml").exists());

    let generated = fs::read_to_string(&generated_path).expect("generated model");
    assert!(
        generated.starts_with(
            "# c4/model.generated.yml\n# Regenerated by c4lens. Do not hand-edit; edit c4/model.yml instead.\n# yaml-language-server: $schema=./schema.json\n"
        )
    );
    assert!(generated.contains("name: "));
    assert!(generated.contains("generated: true"));
    let schema: Value = serde_json::from_str(&fs::read_to_string(&schema_path).expect("schema"))
        .expect("valid schema json");
    assert_eq!(schema["$id"], "https://c4lens.local/schema.json");
    assert_eq!(schema["title"], "c4lens model");
    assert_eq!(schema["properties"]["name"]["type"], "string");
    assert_eq!(
        schema["$defs"]["container"]["properties"]["kind"]["$ref"],
        "#/$defs/containerKind"
    );

    cleanup(repo);
}

#[test]
fn generate_write_preserves_existing_schema_json() {
    let repo = fresh_test_dir("generate-write-existing-schema");
    let schema_path = repo.join("c4/schema.json");
    fs::create_dir_all(schema_path.parent().expect("schema parent")).expect("create c4");
    let existing_schema = "{\"title\": \"pre-existing\"}\n";
    fs::write(&schema_path, existing_schema).expect("write schema");

    Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--write", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let generated_schema = fs::read_to_string(&schema_path).expect("schema");
    assert_eq!(generated_schema, existing_schema);

    cleanup(repo);
}

#[test]
fn generate_write_validates_candidate_before_replacing_existing_overlay() {
    let repo = fresh_test_dir("generate-write-invalid-candidate");
    fs::create_dir_all(repo.join("c4")).expect("create c4");
    fs::write(
        repo.join("c4/model.yml"),
        r#"
name: Existing
actors:
  user:
    name: User
relationships:
  - from: user
    to: missing_target
    description: Missing target
"#,
    )
    .expect("write authored model");
    fs::write(
        repo.join("go.mod"),
        "module github.com/acme/api-service\n\ngo 1.22\n",
    )
    .expect("write go manifest");
    let old_overlay = "name: Old Generated\ngenerated: true\n";
    let generated_path = repo.join("c4/model.generated.yml");
    fs::write(&generated_path, old_overlay).expect("write old generated overlay");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--write", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .code(4);
    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json error");

    assert_eq!(
        payload["issues"][0]["code"],
        "semantic.unresolved_relationship_target"
    );
    assert_eq!(
        fs::read_to_string(&generated_path).expect("old generated overlay"),
        old_overlay
    );
    assert!(!repo.join("c4/schema.json").exists());

    cleanup(repo);
}

#[test]
fn generate_write_validates_candidate_without_reading_existing_overlay_contents() {
    let repo = fresh_test_dir("generate-write-ignores-old-invalid-overlay");
    fs::create_dir_all(repo.join("c4")).expect("create c4");
    fs::write(repo.join("c4/model.generated.yml"), "name: [unterminated\n")
        .expect("write invalid generated overlay");
    fs::write(repo.join("requirements.txt"), "flask==3.0\n").expect("write requirements");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--write", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();
    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json output");

    assert_eq!(payload["ok"], true);
    let generated =
        fs::read_to_string(repo.join("c4/model.generated.yml")).expect("generated overlay");
    assert!(generated.contains("python:"));
    assert!(generated.contains("tech: Python"));

    cleanup(repo);
}

#[cfg(unix)]
#[test]
fn generate_write_rejects_symlinked_schema_json_without_writing_overlay() {
    let repo = fresh_test_dir("generate-write-symlink-schema");
    let outside = fresh_test_dir("generate-write-symlink-schema-outside");
    fs::create_dir_all(repo.join("c4")).expect("create c4");
    let outside_target = outside.join("schema.json");
    fs::write(&outside_target, "outside schema").expect("write outside schema");
    std::os::unix::fs::symlink(&outside_target, repo.join("c4/schema.json"))
        .expect("symlink schema");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--write", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .code(4);
    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json error");

    assert_eq!(payload["issues"][0]["code"], "repo.path_denied");
    assert!(!repo.join("c4/model.generated.yml").exists());
    assert_eq!(
        fs::read_to_string(outside_target).expect("outside schema"),
        "outside schema"
    );
    cleanup(repo);
    cleanup(outside);
}

#[test]
fn generate_check_reports_drift_and_match() {
    let repo = fresh_test_dir("generate-check");
    Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--write", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let match_report = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--check", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();
    let match_payload: Value =
        serde_json::from_slice(&match_report.get_output().stdout).expect("match payload");
    assert_eq!(match_payload["changed"], false);

    let generated_path = repo.join("c4/model.generated.yml");
    fs::write(&generated_path, b"# stale generated model\n").expect("stale model");

    let drift_assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--check", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .code(1);
    let drift_output = String::from_utf8_lossy(&drift_assert.get_output().stdout).to_string();
    let drift_payload: Value =
        serde_json::from_slice(&drift_assert.get_output().stdout).expect("drift payload");

    assert!(drift_output.contains("changed"));
    assert_eq!(drift_payload["ok"], false);
    assert_eq!(drift_payload["changed"], true);

    cleanup(repo);
}

#[test]
fn generate_json_outputs_yaml() {
    let repo = fresh_test_dir("generate-json");
    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let output = assert.get_output();
    let payload: Value = serde_json::from_slice(&output.stdout).expect("valid json");
    assert_eq!(payload["writeRequested"], false);
    assert_eq!(payload["checkRequested"], false);
    assert!(payload["generatedYaml"].as_str().expect("generated yaml").starts_with(
        "# c4/model.generated.yml\n# Regenerated by c4lens. Do not hand-edit; edit c4/model.yml instead.\n# yaml-language-server: $schema=./schema.json\n"
    ));

    cleanup(repo);
}

#[test]
fn generate_with_root_cargo_manifest_returns_generated_system_and_container() {
    let root = fresh_test_dir("generate-root-cargo");
    let repo = root.join("repo");
    fs::create_dir(&repo).expect("create repo");
    fs::create_dir(repo.join("src")).expect("create src");
    fs::write(
        repo.join("Cargo.toml"),
        "[package]\nname = \"cool-service\"\nversion = \"0.1.0\"\n",
    )
    .expect("write cargo manifest");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json output");
    let generated_yaml = payload["generatedYaml"].as_str().expect("generated yaml");

    assert!(generated_yaml.contains("  repo:"));
    assert!(generated_yaml.contains("cool_service:"));
    assert!(generated_yaml.contains("Cool Service"));

    cleanup(root);
}

#[test]
fn generate_with_source_root_directories_returns_generated_components() {
    let root = fresh_test_dir("generate-source-root-components");
    let repo = root.join("repo");
    fs::create_dir(&repo).expect("create repo");
    fs::create_dir_all(repo.join("src/api")).expect("create api");
    fs::create_dir_all(repo.join("src/billing-service")).expect("create billing service");
    fs::create_dir_all(repo.join("src/domain")).expect("create domain");
    fs::create_dir_all(repo.join("src/tests")).expect("create tests");
    fs::create_dir_all(repo.join("src/target")).expect("create target");
    fs::create_dir_all(repo.join("src/.cache")).expect("create hidden");
    fs::write(
        repo.join("Cargo.toml"),
        "[package]\nname = \"billing-service\"\nversion = \"0.1.0\"\n",
    )
    .expect("write cargo manifest");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json output");
    let generated_yaml = payload["generatedYaml"].as_str().expect("generated yaml");

    assert!(generated_yaml.contains("components:"));
    assert!(generated_yaml.contains("api:"));
    assert!(generated_yaml.contains("name: Api"));
    assert!(generated_yaml.contains("code: src/api"));
    assert!(generated_yaml.contains("domain:"));
    assert!(generated_yaml.contains("name: Domain"));
    assert!(generated_yaml.contains("code: src/domain"));
    assert!(generated_yaml.contains("billing_service_2:"));
    assert!(generated_yaml.contains("code: src/billing-service"));
    assert!(!generated_yaml.contains("tests:"));
    assert!(!generated_yaml.contains("target:"));
    assert!(!generated_yaml.contains(".cache"));

    cleanup(root);
}

#[cfg(unix)]
#[test]
fn generate_does_not_emit_components_from_symlinked_source_root() {
    let root = fresh_test_dir("generate-symlinked-source-root-components");
    let repo = root.join("repo");
    let outside = root.join("outside");
    fs::create_dir(&repo).expect("create repo");
    fs::create_dir_all(outside.join("external_component")).expect("create external component");
    std::os::unix::fs::symlink(&outside, repo.join("src")).expect("symlink src");
    fs::write(
        repo.join("Cargo.toml"),
        "[package]\nname = \"billing-service\"\nversion = \"0.1.0\"\n",
    )
    .expect("write cargo manifest");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json output");
    let generated_yaml = payload["generatedYaml"].as_str().expect("generated yaml");

    assert!(generated_yaml.contains("billing_service:"));
    assert!(!generated_yaml.contains("external_component"));

    cleanup(root);
}

#[cfg(unix)]
#[test]
fn generate_skips_component_directories_with_invalid_code_path_names() {
    let root = fresh_test_dir("generate-invalid-component-code-path");
    let repo = root.join("repo");
    fs::create_dir(&repo).expect("create repo");
    fs::create_dir_all(repo.join("src/api")).expect("create api");
    fs::create_dir_all(repo.join("src/bad\\name")).expect("create invalid code path dir");
    fs::write(
        repo.join("Cargo.toml"),
        "[package]\nname = \"billing-service\"\nversion = \"0.1.0\"\n",
    )
    .expect("write cargo manifest");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json output");
    let generated_yaml = payload["generatedYaml"].as_str().expect("generated yaml");

    assert!(generated_yaml.contains("api:"));
    assert!(!generated_yaml.contains("bad_name"));
    assert!(!generated_yaml.contains(r"bad\name"));

    cleanup(root);
}

#[test]
fn generate_with_root_package_json_manifest_returns_generated_system_and_container() {
    let root = fresh_test_dir("generate-root-package-json");
    let repo = root.join("repo");
    fs::create_dir(&repo).expect("create repo");
    fs::create_dir(repo.join("app")).expect("create app");
    fs::write(repo.join("package.json"), r#"{"name": "@acme/web-client"}"#)
        .expect("write package manifest");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json output");
    let generated_yaml = payload["generatedYaml"].as_str().expect("generated yaml");

    assert!(generated_yaml.contains("acme_web_client:"));
    assert!(generated_yaml.contains("Acme Web Client"));
    assert!(generated_yaml.contains("tech: Node.js"));
    assert!(generated_yaml.contains("code: app"));

    cleanup(root);
}

#[test]
fn generate_with_root_pom_xml_manifest_returns_generated_system_and_container() {
    let root = fresh_test_dir("generate-root-pom-xml");
    let repo = root.join("repo");
    fs::create_dir(&repo).expect("create repo");
    fs::create_dir_all(repo.join("src/main/java")).expect("create java source root");
    fs::write(
        repo.join("pom.xml"),
        r#"
<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.acme</groupId>
  <artifactId>billing-api</artifactId>
  <version>0.1.0</version>
</project>
"#,
    )
    .expect("write pom manifest");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json output");
    let generated_yaml = payload["generatedYaml"].as_str().expect("generated yaml");

    assert!(generated_yaml.contains("billing_api:"));
    assert!(generated_yaml.contains("Billing Api"));
    assert!(generated_yaml.contains("tech: Java"));
    assert!(generated_yaml.contains("code: src/main"));

    cleanup(root);
}

#[test]
fn generate_with_root_build_gradle_manifest_returns_generated_system_and_container() {
    let root = fresh_test_dir("generate-root-build-gradle");
    let repo = root.join("repo");
    fs::create_dir(&repo).expect("create repo");
    fs::create_dir_all(repo.join("src/main/java")).expect("create java source root");
    fs::write(
        repo.join("build.gradle"),
        r#"
plugins {
  id 'java'
}

rootProject.name = 'orders-app'
"#,
    )
    .expect("write gradle manifest");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json output");
    let generated_yaml = payload["generatedYaml"].as_str().expect("generated yaml");

    assert!(generated_yaml.contains("orders_app:"));
    assert!(generated_yaml.contains("Orders App"));
    assert!(generated_yaml.contains("tech: Java"));
    assert!(generated_yaml.contains("code: src/main"));

    cleanup(root);
}

#[test]
fn generate_with_root_java_manifests_returns_single_generated_container() {
    let root = fresh_test_dir("generate-root-java-manifest-dedupe");
    let repo = root.join("repo");
    fs::create_dir(&repo).expect("create repo");
    fs::create_dir_all(repo.join("src/main/java")).expect("create java source root");
    fs::write(
        repo.join("pom.xml"),
        r#"
<project>
  <modelVersion>4.0.0</modelVersion>
  <artifactId>billing-api</artifactId>
</project>
"#,
    )
    .expect("write pom manifest");
    fs::write(
        repo.join("build.gradle"),
        r#"
plugins {
  id 'java'
}

rootProject.name = 'orders-app'
"#,
    )
    .expect("write gradle manifest");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json output");
    let generated_yaml = payload["generatedYaml"].as_str().expect("generated yaml");

    assert!(generated_yaml.contains("billing_api:"));
    assert!(generated_yaml.contains("tech: Java"));
    assert!(generated_yaml.contains("code: src/main"));
    assert!(!generated_yaml.contains("orders_app:"));
    assert_eq!(generated_yaml.matches("tech: Java").count(), 1);

    cleanup(root);
}

#[test]
fn generate_with_root_dockerfile_returns_fallback_generated_container() {
    let root = fresh_test_dir("generate-root-dockerfile");
    let repo = root.join("repo");
    fs::create_dir(&repo).expect("create repo");
    fs::write(repo.join("Dockerfile"), "FROM alpine:3.20\n").expect("write dockerfile");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json output");
    let generated_yaml = payload["generatedYaml"].as_str().expect("generated yaml");

    assert!(generated_yaml.contains("dockerfile:"));
    assert!(generated_yaml.contains("name: Dockerfile"));
    assert!(generated_yaml.contains("tech: Docker"));
    assert!(generated_yaml.contains("code: ."));

    cleanup(root);
}

#[test]
fn generate_with_root_dockerfile_and_manifest_does_not_duplicate_container() {
    let root = fresh_test_dir("generate-root-dockerfile-covered");
    let repo = root.join("repo");
    fs::create_dir(&repo).expect("create repo");
    fs::create_dir(repo.join("src")).expect("create src");
    fs::write(
        repo.join("Cargo.toml"),
        "[package]\nname = \"billing-service\"\nversion = \"0.1.0\"\n",
    )
    .expect("write cargo manifest");
    fs::write(repo.join("Dockerfile"), "FROM rust:1.80\n").expect("write dockerfile");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json output");
    let generated_yaml = payload["generatedYaml"].as_str().expect("generated yaml");

    assert!(generated_yaml.contains("billing_service:"));
    assert!(generated_yaml.contains("tech: Rust"));
    assert!(!generated_yaml.contains("dockerfile:"));
    assert!(!generated_yaml.contains("tech: Docker"));

    cleanup(root);
}

#[test]
fn generate_with_package_json_dependencies_returns_external_targets_and_relationships() {
    let root = fresh_test_dir("generate-package-json-dependencies");
    let repo = root.join("repo");
    fs::create_dir(&repo).expect("create repo");
    fs::create_dir(repo.join("app")).expect("create app");
    fs::write(
        repo.join("package.json"),
        r#"{
  "name": "@acme/web-client",
  "dependencies": {
    "stripe": "^14.0.0",
    "redis": "^4.0.0",
    "pg": "^8.0.0",
    "postgres": "^3.0.0",
    "left-pad": "^1.3.0"
  }
}"#,
    )
    .expect("write package manifest");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json output");
    let generated_yaml = payload["generatedYaml"].as_str().expect("generated yaml");

    assert!(generated_yaml.contains("acme_web_client:"));
    assert!(generated_yaml.contains("stripe:"));
    assert!(generated_yaml.contains("name: Stripe"));
    assert!(generated_yaml.contains("external: true"));
    assert!(generated_yaml.contains("redis:"));
    assert!(generated_yaml.contains("name: Redis"));
    assert!(generated_yaml.contains("postgres:"));
    assert!(generated_yaml.contains("name: Postgres"));
    assert_eq!(generated_yaml.matches("kind: store").count(), 2);
    assert!(generated_yaml.contains("relationships:"));
    assert!(generated_yaml.contains("from: acme_web_client"));
    assert!(generated_yaml.contains("description: Uses stripe"));
    assert!(generated_yaml.contains("description: Uses redis"));
    assert!(generated_yaml.contains("description: Uses postgres"));
    assert_eq!(generated_yaml.matches("to: stripe").count(), 1);
    assert_eq!(generated_yaml.matches("to: redis").count(), 1);
    assert_eq!(generated_yaml.matches("to: postgres").count(), 1);
    assert!(!generated_yaml.contains("left_pad"));

    cleanup(root);
}

#[test]
fn generate_renames_store_dependency_when_authored_container_is_not_store() {
    let root = fresh_test_dir("generate-package-json-store-kind-collision");
    let repo = root.join("repo");
    fs::create_dir(&repo).expect("create repo");
    fs::create_dir_all(repo.join("c4")).expect("create c4");
    fs::create_dir(repo.join("app")).expect("create app");
    fs::write(
        repo.join("c4/model.yml"),
        r#"
name: Repo
systems:
  platform:
    name: Platform
    containers:
      redis:
        name: Redis Service Facade
"#,
    )
    .expect("write authored model");
    fs::write(
        repo.join("package.json"),
        r#"{
  "name": "@acme/web-client",
  "dependencies": {
    "redis": "^4.0.0"
  }
}"#,
    )
    .expect("write package manifest");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json output");
    let generated_yaml = payload["generatedYaml"].as_str().expect("generated yaml");

    assert!(generated_yaml.contains("platform:"));
    assert!(generated_yaml.contains("redis_2:"));
    assert!(generated_yaml.contains("name: Redis"));
    assert!(generated_yaml.contains("kind: store"));
    assert!(generated_yaml.contains("to: redis_2"));
    assert!(!generated_yaml.contains("to: redis\n"));

    cleanup(root);
}

#[test]
fn generate_renames_external_dependency_when_authored_system_is_internal() {
    let root = fresh_test_dir("generate-package-json-external-internal-collision");
    let repo = root.join("repo");
    fs::create_dir(&repo).expect("create repo");
    fs::create_dir_all(repo.join("c4")).expect("create c4");
    fs::create_dir(repo.join("app")).expect("create app");
    fs::write(
        repo.join("c4/model.yml"),
        r#"
name: Repo
systems:
  platform:
    name: Platform
  stripe:
    name: Internal Stripe Adapter
"#,
    )
    .expect("write authored model");
    fs::write(
        repo.join("package.json"),
        r#"{
  "name": "@acme/web-client",
  "dependencies": {
    "stripe": "^14.0.0"
  }
}"#,
    )
    .expect("write package manifest");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json output");
    let generated_yaml = payload["generatedYaml"].as_str().expect("generated yaml");

    assert!(generated_yaml.contains("stripe_2:"));
    assert!(generated_yaml.contains("name: Stripe"));
    assert!(generated_yaml.contains("external: true"));
    assert!(generated_yaml.contains("to: stripe_2"));
    assert!(!generated_yaml.contains("to: stripe\n"));

    cleanup(root);
}

#[test]
fn generate_reuses_authored_store_dependency_under_reused_internal_system() {
    let root = fresh_test_dir("generate-package-json-authored-store-reuse");
    let repo = root.join("repo");
    fs::create_dir(&repo).expect("create repo");
    fs::create_dir_all(repo.join("c4")).expect("create c4");
    fs::create_dir(repo.join("app")).expect("create app");
    fs::write(
        repo.join("c4/model.yml"),
        r#"
name: Repo
systems:
  platform:
    name: Platform
    containers:
      redis:
        name: Redis
        kind: store
"#,
    )
    .expect("write authored model");
    fs::write(
        repo.join("package.json"),
        r#"{
  "name": "@acme/web-client",
  "dependencies": {
    "redis": "^4.0.0"
  }
}"#,
    )
    .expect("write package manifest");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json output");
    let generated_yaml = payload["generatedYaml"].as_str().expect("generated yaml");

    assert!(generated_yaml.contains("platform:"));
    assert!(!generated_yaml.contains("      redis:\n"));
    assert!(!generated_yaml.contains("redis_2:"));
    assert!(generated_yaml.contains("to: redis"));

    cleanup(root);
}

#[test]
fn generate_reuses_single_authored_internal_system_for_generated_containers() {
    let root = fresh_test_dir("generate-reuses-authored-system");
    let repo = root.join("repo");
    fs::create_dir(&repo).expect("create repo");
    fs::create_dir_all(repo.join("c4")).expect("create c4");
    fs::create_dir(repo.join("src")).expect("create src");
    fs::write(
        repo.join("c4/model.yml"),
        r#"
name: Authored Model
systems:
  billing:
    name: Billing Platform
"#,
    )
    .expect("write authored model");
    fs::write(repo.join("c4/model.generated.yml"), "name: [broken\n")
        .expect("write malformed generated overlay");
    fs::write(
        repo.join("Cargo.toml"),
        "[package]\nname = \"invoice-api\"\nversion = \"0.1.0\"\n",
    )
    .expect("write cargo manifest");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json output");
    let generated_yaml = payload["generatedYaml"].as_str().expect("generated yaml");

    assert!(generated_yaml.contains("  billing:"));
    assert!(generated_yaml.contains("name: Billing Platform"));
    assert!(generated_yaml.contains("invoice_api:"));
    assert!(!generated_yaml.contains("  repo:"));

    cleanup(root);
}

#[test]
fn generate_write_reuses_single_authored_internal_system_with_malformed_existing_overlay() {
    let root = fresh_test_dir("generate-write-reuses-authored-system");
    let repo = root.join("repo");
    fs::create_dir(&repo).expect("create repo");
    fs::create_dir_all(repo.join("c4")).expect("create c4");
    fs::create_dir(repo.join("src")).expect("create src");
    fs::write(
        repo.join("c4/model.yml"),
        r#"
name: Authored Model
systems:
  billing:
    name: Billing Platform
"#,
    )
    .expect("write authored model");
    fs::write(repo.join("c4/model.generated.yml"), "name: [broken\n")
        .expect("write malformed generated overlay");
    fs::write(
        repo.join("Cargo.toml"),
        "[package]\nname = \"invoice-api\"\nversion = \"0.1.0\"\n",
    )
    .expect("write cargo manifest");

    Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--write", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let generated_yaml =
        fs::read_to_string(repo.join("c4/model.generated.yml")).expect("generated yaml");
    assert!(generated_yaml.contains("  billing:"));
    assert!(generated_yaml.contains("name: Billing Platform"));
    assert!(generated_yaml.contains("invoice_api:"));
    assert!(!generated_yaml.contains("  repo:"));

    cleanup(root);
}

#[test]
fn generate_write_renames_generated_container_when_authored_actor_slug_collides() {
    let root = fresh_test_dir("generate-write-authored-actor-collision");
    let repo = root.join("repo");
    fs::create_dir(&repo).expect("create repo");
    fs::create_dir_all(repo.join("c4")).expect("create c4");
    fs::write(
        repo.join("c4/model.yml"),
        r#"
name: Authored Model
actors:
  api_service:
    name: API Service Actor
"#,
    )
    .expect("write authored model");
    fs::write(
        repo.join("go.mod"),
        "module github.com/acme/api-service\n\ngo 1.22\n",
    )
    .expect("write go manifest");

    Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--write", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let generated_yaml =
        fs::read_to_string(repo.join("c4/model.generated.yml")).expect("generated yaml");
    assert!(generated_yaml.contains("api_service_2:"));
    assert!(!generated_yaml.contains("api_service:\n"));

    cleanup(root);
}

#[test]
fn generate_keeps_generated_container_slug_when_matching_authored_container_parent() {
    let root = fresh_test_dir("generate-keep-authored-container-match");
    let repo = root.join("repo");
    fs::create_dir(&repo).expect("create repo");
    fs::create_dir_all(repo.join("c4")).expect("create c4");
    fs::write(
        repo.join("c4/model.yml"),
        r#"
name: Authored Model
systems:
  billing:
    name: Billing Platform
    containers:
      api_service:
        name: Authored API Service
"#,
    )
    .expect("write authored model");
    fs::write(
        repo.join("go.mod"),
        "module github.com/acme/api-service\n\ngo 1.22\n",
    )
    .expect("write go manifest");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json output");
    let generated_yaml = payload["generatedYaml"].as_str().expect("generated yaml");

    assert!(generated_yaml.contains("  billing:"));
    assert!(generated_yaml.contains("api_service:"));
    assert!(!generated_yaml.contains("api_service_2:"));

    cleanup(root);
}

#[test]
fn generate_renames_generated_container_when_authored_container_parent_differs() {
    let root = fresh_test_dir("generate-authored-container-different-parent-collision");
    let repo = root.join("repo");
    fs::create_dir(&repo).expect("create repo");
    fs::create_dir_all(repo.join("c4")).expect("create c4");
    fs::write(
        repo.join("c4/model.yml"),
        r#"
name: Authored Model
systems:
  authored_system:
    name: Authored System
    containers:
      api_service:
        name: Authored API Service
  another_system:
    name: Another System
"#,
    )
    .expect("write authored model");
    fs::write(
        repo.join("go.mod"),
        "module github.com/acme/api-service\n\ngo 1.22\n",
    )
    .expect("write go manifest");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json output");
    let generated_yaml = payload["generatedYaml"].as_str().expect("generated yaml");

    assert!(generated_yaml.contains("  repo:"));
    assert!(generated_yaml.contains("api_service_2:"));
    assert!(!generated_yaml.contains("api_service:\n"));

    cleanup(root);
}

#[test]
fn generate_suffix_collision_does_not_merge_unrelated_authored_container() {
    let root = fresh_test_dir("generate-suffix-skips-authored-container");
    let repo = root.join("repo");
    fs::create_dir(&repo).expect("create repo");
    fs::create_dir_all(repo.join("c4")).expect("create c4");
    fs::write(
        repo.join("c4/model.yml"),
        r#"
name: Authored Model
actors:
  api_service:
    name: API Service Actor
systems:
  repo:
    name: Repo
    containers:
      api_service_2:
        name: Authored API Service 2
"#,
    )
    .expect("write authored model");
    fs::write(
        repo.join("go.mod"),
        "module github.com/acme/api-service\n\ngo 1.22\n",
    )
    .expect("write go manifest");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json output");
    let generated_yaml = payload["generatedYaml"].as_str().expect("generated yaml");

    assert!(generated_yaml.contains("api_service_3:"));
    assert!(!generated_yaml.contains("api_service_2:\n"));

    cleanup(root);
}

#[test]
fn generate_falls_back_to_repo_system_when_authored_system_is_invalid() {
    let root = fresh_test_dir("generate-invalid-authored-system");
    let repo = root.join("repo");
    fs::create_dir(&repo).expect("create repo");
    fs::create_dir_all(repo.join("c4")).expect("create c4");
    fs::create_dir(repo.join("src")).expect("create src");
    fs::write(
        repo.join("c4/model.yml"),
        r#"
name: Authored Model
systems:
  Billing:
    name: Billing Platform
"#,
    )
    .expect("write invalid authored model");
    fs::write(
        repo.join("Cargo.toml"),
        "[package]\nname = \"invoice-api\"\nversion = \"0.1.0\"\n",
    )
    .expect("write cargo manifest");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json output");
    let generated_yaml = payload["generatedYaml"].as_str().expect("generated yaml");

    assert!(generated_yaml.contains("  repo:"));
    assert!(!generated_yaml.contains("  Billing:"));

    cleanup(root);
}

#[test]
fn generate_uses_repo_system_when_authored_system_selection_is_ambiguous() {
    let root = fresh_test_dir("generate-ambiguous-authored-system");
    let repo = root.join("repo");
    fs::create_dir(&repo).expect("create repo");
    fs::create_dir_all(repo.join("c4")).expect("create c4");
    fs::create_dir(repo.join("src")).expect("create src");
    fs::write(
        repo.join("c4/model.yml"),
        r#"
name: Authored Model
systems:
  billing:
    name: Billing Platform
  fulfillment:
    name: Fulfillment Platform
"#,
    )
    .expect("write ambiguous authored model");
    fs::write(
        repo.join("Cargo.toml"),
        "[package]\nname = \"invoice-api\"\nversion = \"0.1.0\"\n",
    )
    .expect("write cargo manifest");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json output");
    let generated_yaml = payload["generatedYaml"].as_str().expect("generated yaml");

    assert!(generated_yaml.contains("  repo:"));
    assert!(!generated_yaml.contains("  billing:"));
    assert!(!generated_yaml.contains("  fulfillment:"));

    cleanup(root);
}

#[test]
fn generate_uses_repo_system_when_authored_system_is_external_only() {
    let root = fresh_test_dir("generate-external-authored-system");
    let repo = root.join("repo");
    fs::create_dir(&repo).expect("create repo");
    fs::create_dir_all(repo.join("c4")).expect("create c4");
    fs::create_dir(repo.join("src")).expect("create src");
    fs::write(
        repo.join("c4/model.yml"),
        r#"
name: Authored Model
systems:
  stripe:
    name: Stripe
    external: true
"#,
    )
    .expect("write external authored model");
    fs::write(
        repo.join("Cargo.toml"),
        "[package]\nname = \"invoice-api\"\nversion = \"0.1.0\"\n",
    )
    .expect("write cargo manifest");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json output");
    let generated_yaml = payload["generatedYaml"].as_str().expect("generated yaml");

    assert!(generated_yaml.contains("  repo:"));
    assert!(!generated_yaml.contains("  stripe:"));

    cleanup(root);
}

#[test]
fn generate_with_root_go_mod_manifest_returns_generated_system_and_container() {
    let root = fresh_test_dir("generate-root-go-mod");
    let repo = root.join("repo");
    fs::create_dir(&repo).expect("create repo");
    fs::create_dir(repo.join("src")).expect("create src");
    fs::write(
        repo.join("go.mod"),
        "module github.com/acme/api-service\n\ngo 1.22\n",
    )
    .expect("write go manifest");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json output");
    let generated_yaml = payload["generatedYaml"].as_str().expect("generated yaml");

    assert!(generated_yaml.contains("api_service:"));
    assert!(generated_yaml.contains("Api Service"));
    assert!(generated_yaml.contains("tech: Go"));
    assert!(generated_yaml.contains("code: src"));

    cleanup(root);
}

#[test]
fn generate_with_root_pyproject_toml_manifest_returns_generated_system_and_container() {
    let root = fresh_test_dir("generate-root-pyproject-toml");
    let repo = root.join("web-service");
    fs::create_dir(&repo).expect("create repo");
    fs::create_dir(repo.join("src")).expect("create src");
    fs::write(
        repo.join("pyproject.toml"),
        r#"[project]
name = "data-portal"
version = "0.1.0"
"#,
    )
    .expect("write pyproject manifest");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json output");
    let generated_yaml = payload["generatedYaml"].as_str().expect("generated yaml");

    assert!(generated_yaml.contains("data_portal:"));
    assert!(generated_yaml.contains("Data Portal"));
    assert!(generated_yaml.contains("tech: Python"));
    assert!(generated_yaml.contains("code: src"));

    cleanup(root);
}

#[test]
fn generate_with_root_requirements_txt_manifest_returns_fallback_python_container_when_no_pyproject(
) {
    let root = fresh_test_dir("generate-root-requirements-fallback");
    let repo = root.join("repo");
    fs::create_dir(&repo).expect("create repo");
    fs::write(repo.join("requirements.txt"), "flask==3.0\n").expect("write requirements");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json output");
    let generated_yaml = payload["generatedYaml"].as_str().expect("generated yaml");

    assert!(generated_yaml.contains("python:"));
    assert!(generated_yaml.contains("name: Python"));
    assert!(generated_yaml.contains("tech: Python"));

    cleanup(root);
}

#[test]
fn generate_with_root_gemfile_manifest_uses_rails_tech() {
    let root = fresh_test_dir("generate-root-gemfile-rails");
    let repo = root.join("repo");
    fs::create_dir(&repo).expect("create repo");
    fs::create_dir(repo.join("app")).expect("create app");
    fs::write(
        repo.join("Gemfile"),
        "source 'https://rubygems.org'\ngem 'rails', '~> 7.1'\n",
    )
    .expect("write gemfile");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json output");
    let generated_yaml = payload["generatedYaml"].as_str().expect("generated yaml");

    assert!(generated_yaml.contains("ruby:"));
    assert!(generated_yaml.contains("tech: Ruby on Rails"));
    assert!(generated_yaml.contains("code: app"));

    cleanup(root);
}

#[test]
fn generate_write_reports_write_locked_when_writer_is_active() {
    let repo = fresh_test_dir("generate-write-locked");
    let lock = acquire_repo_write_lock(&repo_handle_from_path(&repo).expect("repo handle"))
        .expect("preacquired lock");
    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--write", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .code(3);
    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json error");

    assert_eq!(payload["issues"][0]["code"], "repo.write_locked");
    drop(lock);
    cleanup(repo);
}

#[test]
fn generate_read_only_json_succeeds_when_writer_is_active() {
    let repo = fresh_test_dir("generate-read-only-locked");
    let lock = acquire_repo_write_lock(&repo_handle_from_path(&repo).expect("repo handle"))
        .expect("preacquired lock");
    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();
    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json output");

    assert_eq!(payload["writeRequested"], false);
    assert!(payload["generatedYaml"].as_str().is_some());
    assert!(!repo.join("c4/model.generated.yml").exists());

    drop(lock);
    cleanup(repo);
}

#[test]
fn generate_check_succeeds_when_writer_is_active() {
    let repo = fresh_test_dir("generate-check-locked");
    Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--write", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let lock = acquire_repo_write_lock(&repo_handle_from_path(&repo).expect("repo handle"))
        .expect("preacquired lock");
    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--check", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();
    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json output");

    assert_eq!(payload["writeRequested"], false);
    assert_eq!(payload["checkRequested"], true);
    assert_eq!(payload["changed"], false);

    drop(lock);
    cleanup(repo);
}

#[test]
fn generate_check_and_write_is_invalid_usage() {
    let repo = fresh_test_dir("generate-check-write");

    Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--check", "--write", "--repo"])
        .arg(&repo)
        .assert()
        .code(2);

    assert!(!repo.join("c4/model.generated.yml").exists());
    cleanup(repo);
}

#[cfg(unix)]
#[test]
fn generate_write_rejects_symlinked_c4_directory() {
    let repo = fresh_test_dir("generate-write-symlink-c4");
    let outside = fresh_test_dir("generate-write-symlink-c4-outside");
    std::os::unix::fs::symlink(&outside, repo.join("c4")).expect("symlink c4");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--write", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .code(4);
    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json error");

    assert_eq!(payload["issues"][0]["code"], "repo.path_denied");
    assert!(!outside.join("model.generated.yml").exists());
    assert!(!repo.join("c4/schema.json").exists());
    assert!(!repo.join("c4/model.generated.yml").exists());
    cleanup(repo);
    cleanup(outside);
}

#[cfg(unix)]
#[test]
fn generate_write_rejects_symlinked_generated_overlay() {
    let repo = fresh_test_dir("generate-write-symlink-overlay");
    let outside = fresh_test_dir("generate-write-symlink-overlay-outside");
    fs::create_dir_all(repo.join("c4")).expect("create c4");
    let outside_target = outside.join("target.yml");
    fs::write(&outside_target, "outside").expect("write outside target");
    std::os::unix::fs::symlink(&outside_target, repo.join("c4/model.generated.yml"))
        .expect("symlink overlay");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--write", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .code(4);
    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json error");

    assert_eq!(payload["issues"][0]["code"], "repo.path_denied");
    assert!(!repo.join("c4/schema.json").exists());
    assert_eq!(
        fs::read_to_string(outside_target).expect("outside target"),
        "outside"
    );
    cleanup(repo);
    cleanup(outside);
}

#[cfg(unix)]
#[test]
fn generate_check_rejects_symlinked_overlay_without_disclosing_target() {
    let repo = fresh_test_dir("generate-check-symlink-overlay");
    let outside = fresh_test_dir("generate-check-symlink-overlay-outside");
    fs::create_dir_all(repo.join("c4")).expect("create c4");
    let outside_target = outside.join("target.yml");
    fs::write(&outside_target, "outside secret generated yaml").expect("write outside target");
    std::os::unix::fs::symlink(&outside_target, repo.join("c4/model.generated.yml"))
        .expect("symlink overlay");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--check", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .code(4);
    let output = String::from_utf8_lossy(&assert.get_output().stdout);
    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json error");

    assert_eq!(payload["issues"][0]["code"], "repo.path_denied");
    assert!(!output.contains("outside secret generated yaml"));
    cleanup(repo);
    cleanup(outside);
}

fn fresh_test_dir(name: &str) -> PathBuf {
    let unique = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("system time")
        .as_nanos();
    let root = std::env::temp_dir().join(format!("c4lens-cli-generate-{name}-{unique}"));
    fs::create_dir_all(&root).expect("create test root");
    root
}

fn cleanup(root: PathBuf) {
    fs::remove_dir_all(root).ok();
}
