use std::fs;
use std::path::PathBuf;
use std::time::{SystemTime, UNIX_EPOCH};

use assert_cmd::Command;
use serde_json::Value;

#[test]
fn generate_does_not_write_without_write_flag() {
    let repo = fresh_test_dir("generate-non-write");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--repo"])
        .arg(&repo)
        .assert()
        .success();
    let output = String::from_utf8_lossy(&assert.get_output().stdout).to_string();

    assert!(
        output.starts_with(
            "# c4/model.generated.yml\n# Regenerated by c4lens. Do not hand-edit; edit c4/model.yml instead.\n# yaml-language-server: $schema=./schema.json\n"
        )
    );
    assert!(!repo.join("c4").is_dir());

    cleanup(repo);
}

#[test]
fn generate_write_creates_generated_overlay_without_model_yaml() {
    let repo = fresh_test_dir("generate-write");

    Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--write", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let generated_path = repo.join("c4/model.generated.yml");
    assert!(generated_path.is_file());
    assert!(!repo.join("c4/model.yml").exists());

    let generated = fs::read_to_string(&generated_path).expect("generated model");
    assert!(
        generated.starts_with(
            "# c4/model.generated.yml\n# Regenerated by c4lens. Do not hand-edit; edit c4/model.yml instead.\n# yaml-language-server: $schema=./schema.json\n"
        )
    );
    assert!(generated.contains("name: "));
    assert!(generated.contains("generated: true"));

    cleanup(repo);
}

#[test]
fn generate_check_reports_drift_and_match() {
    let repo = fresh_test_dir("generate-check");
    Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--write", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let match_report = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--check", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();
    let match_payload: Value =
        serde_json::from_slice(&match_report.get_output().stdout).expect("match payload");
    assert_eq!(match_payload["changed"], false);

    let generated_path = repo.join("c4/model.generated.yml");
    fs::write(&generated_path, b"# stale generated model\n").expect("stale model");

    let drift_assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--check", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .code(1);
    let drift_output = String::from_utf8_lossy(&drift_assert.get_output().stdout).to_string();
    let drift_payload: Value =
        serde_json::from_slice(&drift_assert.get_output().stdout).expect("drift payload");

    assert!(drift_output.contains("changed"));
    assert_eq!(drift_payload["ok"], false);
    assert_eq!(drift_payload["changed"], true);

    cleanup(repo);
}

#[test]
fn generate_json_outputs_yaml() {
    let repo = fresh_test_dir("generate-json");
    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let output = assert.get_output();
    let payload: Value = serde_json::from_slice(&output.stdout).expect("valid json");
    assert_eq!(payload["writeRequested"], false);
    assert_eq!(payload["checkRequested"], false);
    assert!(payload["generatedYaml"].as_str().expect("generated yaml").starts_with(
        "# c4/model.generated.yml\n# Regenerated by c4lens. Do not hand-edit; edit c4/model.yml instead.\n# yaml-language-server: $schema=./schema.json\n"
    ));

    cleanup(repo);
}

#[test]
fn generate_with_root_cargo_manifest_returns_generated_system_and_container() {
    let root = fresh_test_dir("generate-root-cargo");
    let repo = root.join("repo");
    fs::create_dir(&repo).expect("create repo");
    fs::create_dir(repo.join("src")).expect("create src");
    fs::write(
        repo.join("Cargo.toml"),
        "[package]\nname = \"cool-service\"\nversion = \"0.1.0\"\n",
    )
    .expect("write cargo manifest");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json output");
    let generated_yaml = payload["generatedYaml"].as_str().expect("generated yaml");

    assert!(generated_yaml.contains("  repo:"));
    assert!(generated_yaml.contains("cool_service:"));
    assert!(generated_yaml.contains("Cool Service"));

    cleanup(root);
}

#[test]
fn generate_with_root_package_json_manifest_returns_generated_system_and_container() {
    let root = fresh_test_dir("generate-root-package-json");
    let repo = root.join("repo");
    fs::create_dir(&repo).expect("create repo");
    fs::create_dir(repo.join("app")).expect("create app");
    fs::write(repo.join("package.json"), r#"{"name": "@acme/web-client"}"#)
        .expect("write package manifest");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .success();

    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json output");
    let generated_yaml = payload["generatedYaml"].as_str().expect("generated yaml");

    assert!(generated_yaml.contains("acme_web_client:"));
    assert!(generated_yaml.contains("Acme Web Client"));
    assert!(generated_yaml.contains("tech: Node.js"));
    assert!(generated_yaml.contains("code: app"));

    cleanup(root);
}

#[test]
fn generate_check_and_write_is_invalid_usage() {
    let repo = fresh_test_dir("generate-check-write");

    Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--check", "--write", "--repo"])
        .arg(&repo)
        .assert()
        .code(2);

    assert!(!repo.join("c4/model.generated.yml").exists());
    cleanup(repo);
}

#[cfg(unix)]
#[test]
fn generate_write_rejects_symlinked_c4_directory() {
    let repo = fresh_test_dir("generate-write-symlink-c4");
    let outside = fresh_test_dir("generate-write-symlink-c4-outside");
    std::os::unix::fs::symlink(&outside, repo.join("c4")).expect("symlink c4");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--write", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .code(4);
    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json error");

    assert_eq!(payload["issues"][0]["code"], "repo.path_denied");
    assert!(!outside.join("model.generated.yml").exists());
    cleanup(repo);
    cleanup(outside);
}

#[cfg(unix)]
#[test]
fn generate_write_rejects_symlinked_generated_overlay() {
    let repo = fresh_test_dir("generate-write-symlink-overlay");
    let outside = fresh_test_dir("generate-write-symlink-overlay-outside");
    fs::create_dir_all(repo.join("c4")).expect("create c4");
    let outside_target = outside.join("target.yml");
    fs::write(&outside_target, "outside").expect("write outside target");
    std::os::unix::fs::symlink(&outside_target, repo.join("c4/model.generated.yml"))
        .expect("symlink overlay");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--write", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .code(4);
    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json error");

    assert_eq!(payload["issues"][0]["code"], "repo.path_denied");
    assert_eq!(
        fs::read_to_string(outside_target).expect("outside target"),
        "outside"
    );
    cleanup(repo);
    cleanup(outside);
}

#[cfg(unix)]
#[test]
fn generate_check_rejects_symlinked_overlay_without_disclosing_target() {
    let repo = fresh_test_dir("generate-check-symlink-overlay");
    let outside = fresh_test_dir("generate-check-symlink-overlay-outside");
    fs::create_dir_all(repo.join("c4")).expect("create c4");
    let outside_target = outside.join("target.yml");
    fs::write(&outside_target, "outside secret generated yaml").expect("write outside target");
    std::os::unix::fs::symlink(&outside_target, repo.join("c4/model.generated.yml"))
        .expect("symlink overlay");

    let assert = Command::cargo_bin("c4lens-cli")
        .expect("binary")
        .args(["generate", "--check", "--json", "--repo"])
        .arg(&repo)
        .assert()
        .code(4);
    let output = String::from_utf8_lossy(&assert.get_output().stdout);
    let payload: Value = serde_json::from_slice(&assert.get_output().stdout).expect("json error");

    assert_eq!(payload["issues"][0]["code"], "repo.path_denied");
    assert!(!output.contains("outside secret generated yaml"));
    cleanup(repo);
    cleanup(outside);
}

fn fresh_test_dir(name: &str) -> PathBuf {
    let unique = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("system time")
        .as_nanos();
    let root = std::env::temp_dir().join(format!("c4lens-cli-generate-{name}-{unique}"));
    fs::create_dir_all(&root).expect("create test root");
    root
}

fn cleanup(root: PathBuf) {
    fs::remove_dir_all(root).ok();
}
