import type { EffectiveModel, ElementNode, Relationship } from "./types";

const elementsBySlug: Record<string, ElementNode> = {
  customer: {
    slug: "customer",
    name: "Customer",
    description: "People using Acme services.",
    status: "live",
    generated: false,
    type: "actor",
    source: "merged",
  },
  acme_api: {
    slug: "acme_api",
    name: "Acme API",
    description: "HTTP API providing business capabilities.",
    tech: "Rust",
    status: "live",
    code: "src/api",
    generated: false,
    type: "system",
    systemSlug: "acme_api",
    external: false,
    source: "merged",
  },
  payments: {
    slug: "payments",
    name: "Payments",
    description: "External payment provider integration.",
    tech: "Stripe",
    status: "live",
    generated: false,
    type: "system",
    systemSlug: "payments",
    external: true,
    source: "merged",
  },
  api_server: {
    slug: "api_server",
    name: "API Server",
    description: "Public request handler cluster.",
    tech: "Axum",
    status: "live",
    code: "src/api/server",
    generated: false,
    type: "container",
    parentSlug: "acme_api",
    systemSlug: "acme_api",
    kind: "service",
    source: "merged",
  },
  event_bus: {
    slug: "event_bus",
    name: "Event Bus",
    description: "Durable event stream for async work.",
    tech: "Redis",
    status: "live",
    code: "src/api/events",
    generated: false,
    type: "container",
    parentSlug: "acme_api",
    systemSlug: "acme_api",
    kind: "queue",
    source: "merged",
  },
  auth_component: {
    slug: "auth_component",
    name: "Authentication Component",
    description: "Validates sessions and issues tokens.",
    tech: "JWT",
    status: "live",
    code: "src/api/server/auth",
    generated: false,
    type: "component",
    parentSlug: "api_server",
    systemSlug: "acme_api",
    containerSlug: "api_server",
    source: "merged",
  },
  billing_component: {
    slug: "billing_component",
    name: "Billing Component",
    description: "Invoices and subscription workflows.",
    tech: "Rust",
    status: "live",
    code: "src/api/server/billing",
    generated: false,
    type: "component",
    parentSlug: "api_server",
    systemSlug: "acme_api",
    containerSlug: "api_server",
    source: "merged",
  },
};

const relationships: Relationship[] = [
  {
    from: "customer",
    to: "api_server",
    description: "Uses",
    tech: "HTTPS",
    status: "live",
    generated: false,
  },
  {
    from: "api_server",
    to: "auth_component",
    description: "Authenticates",
    status: "live",
    generated: false,
  },
  {
    from: "api_server",
    to: "billing_component",
    description: "Triggers",
    status: "live",
    generated: false,
  },
  {
    from: "billing_component",
    to: "event_bus",
    description: "Publishes",
    tech: "Jobs",
    status: "live",
    generated: false,
  },
  {
    from: "api_server",
    to: "payments",
    description: "Charges",
    tech: "REST API",
    status: "live",
    generated: false,
  },
];

export const sampleModel: EffectiveModel = {
  repo: {
    id: "sample",
    rootPath: "",
    name: "Sample",
  },
  sourceSha: "sample-phase0-v1",
  model: {
    name: "Acme Demo Platform",
    description: "A phase-0 sample model for desktop onboarding.",
    actors: {
      customer: elementsBySlug.customer,
    },
    systems: {
      acme_api: {
        ...elementsBySlug.acme_api,
        external: false,
        containers: {
          api_server: {
            ...elementsBySlug.api_server,
            kind: "service",
            components: {
              auth_component: elementsBySlug.auth_component,
              billing_component: elementsBySlug.billing_component,
            },
          },
          event_bus: {
            ...elementsBySlug.event_bus,
            kind: "queue",
            components: {},
          },
        },
      },
      payments: {
        ...elementsBySlug.payments,
        external: true,
        containers: {},
      },
    },
    relationships,
    generated: false,
  },
  elementsBySlug,
  relationships,
  validation: {
    ok: true,
    sourceSha: "sample-phase0-v1",
    issues: [
      {
        severity: "warning",
        stage: "schema",
        code: "schema.phase0_placeholder",
        message: "No model files loaded yet. Using phase-0 sample model.",
      },
    ],
  },
};
